CharacterId: 10066
translator: 罐子
title:
  - TextJp: メイド大ピンチ！
    TextCn: 女仆大危机！
    TextKr: 메이드 대 핀치!
    TextEn: ''
    TextTh: ''
    TextTw: ''
    GroupId: 1006602
    FavorScheduleId: 100662
    CharacterId: 10066
    unsure: false
  - TextJp: メイドお勉強大作戦！
    TextCn: 女仆的学习大作战！
    TextKr: 공부! 메이드 대작전!
    TextEn: ''
    TextTh: ''
    TextTw: ''
    GroupId: 1006603
    FavorScheduleId: 100663
    CharacterId: 10066
    unsure: false
  - TextJp: 出撃準備完了！
    TextCn: 出击准备完毕！
    TextKr: 출격 준비 완료!
    TextEn: ''
    TextTh: ''
    TextTw: ''
    GroupId: 1006605
    FavorScheduleId: 100665
    CharacterId: 10066
    unsure: false
content:
  - MessageKR: 우우우…… 우우우……
    MessageJP: うう……先生……
    MessageCN: 呜呜……老师……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660010
    Id: 100660010
    CharacterId: 10066
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 아리스? 왜 그래? 무슨 일 있어?
    MessageJP: アリス、どうしたの？
    MessageCN: 怎么了，爱丽丝？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660020
    Id: 100660020
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 우우우…… 아리스는 도움이 필요합니다.
    MessageJP: アリスを……助けてください
    MessageCN: 请……帮帮爱丽丝
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660030
    Id: 100660030
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660040
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 꼼짝도 할 수 없는 겁니다. 몸에 힘이 들어가지 않습니다……
    MessageJP: あ、いえ、やっぱりなんでもありません！
    MessageCN: 啊，没什么，老师别在意！
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660030
    Id: 100660040
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660040
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 지금 갈게!
    MessageJP: 今行くね！
    MessageCN: 我现在就过去！
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660040
    Id: 100660050
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100662
    NextGroupId: 100660050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 선생님.
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660050
    Id: 100660060
    CharacterId: 10066
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100660040
    PreConditionFavorScheduleId: 100662
    FavorScheduleId: 0
    NextGroupId: 100660060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 아리스는 찾아내고 말았습니다.
    MessageJP: アリス、見つけてしまいました
    MessageCN: 爱丽丝，找到了
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660060
    Id: 100660070
    CharacterId: 10066
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 무엇을……?
    MessageJP: 何を……？
    MessageCN: 找到什么了……？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660070
    Id: 100660080
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그것은 바로, 메이드 레벨을 올리는 새로운 방법입니다.
    MessageJP: メイドレベルを上げる新たな方法です
    MessageCN: 我找到能够提升女仆等级的新方法了
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660080
    Id: 100660090
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660090
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 굉장한 선언을 들은 것 같은 기분이다……
    MessageJP: それってどんな……？
    MessageCN: 具体是……？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660090
    Id: 100660100
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 오늘의 아리스는 다릅니다. 다를 겁니다.
    MessageJP: ずばり
    MessageCN: 单刀直入说的话就是
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660100
    Id: 100660110
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 메이드라는 것은 무엇인가! 어떤 일을 하는가!
    MessageJP: メイドとはなにか！その仕事の実態は！？
    MessageCN: 所谓女仆究竟是什么！其工作的真相又是什么！？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660110
    Id: 100660120
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그것을 공부하는 겁니다, 선생님!
    MessageJP: それを勉強することです！！
    MessageCN: 仔细学习这两个内容就可以了！！
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660110
    Id: 100660130
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660120
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그리고 아리스는, 그러기 위한 자료를 찾아내고야 말았으니까요!
    MessageJP: ちょうどいい資料も見つけましたので
    MessageCN: 我刚好找到了合适的资料呢
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660120
    Id: 100660140
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 메이드 자료?!
    MessageJP: メイドの……資料……？
    MessageCN: 女仆的……资料……？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660130
    Id: 100660150
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100663
    NextGroupId: 100660140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 선생님.
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660140
    Id: 100660160
    CharacterId: 10066
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100660130
    PreConditionFavorScheduleId: 100663
    FavorScheduleId: 0
    NextGroupId: 100660150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 중대한 소식이 있습니다.
    MessageJP: 大事な話があります
    MessageCN: 我有很重要的事想和你说
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660150
    Id: 100660170
    CharacterId: 10066
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 아리스의 중대한 소식……
    MessageJP: アリスの、大事な話……
    MessageCN: 爱丽丝想说的，很重要的事……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660160
    Id: 100660180
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 뭔가 대단한 일이 일어날 것 같은 기분이 든다……
    MessageJP: とんでもないことが起こりそうな予感……
    MessageCN: 感觉会发生不得了的事情啊……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660160
    Id: 100660190
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 정말 중요한 소식입니다.
    MessageJP: とても大事な話なんです
    MessageCN: 真的是非常重要的事
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660170
    Id: 100660200
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그러니까 선생님이 꼭 와 주셨으면 합니다.
    MessageJP: ですから、ぜひ来てほしいのです
    MessageCN: 所以，请务必来找我
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660170
    Id: 100660210
    CharacterId: 10066
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100660180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 큰일이 난 거 아니지!?
    MessageJP: ……うん、すぐに行くね
    MessageCN: ……嗯，我现在就过去
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100660180
    Id: 100660220
    CharacterId: 10066
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100665
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
