CharacterId: 10067
translator: ARUKU
title:
  - TextJp: 理由は後から
    TextCn: 理由之后再说
    TextKr: 문제의 원인
    TextEn: ''
    TextTh: ''
    TextTw: ''
    GroupId: 1006702
    FavorScheduleId: 100672
    CharacterId: 10067
    unsure: false
  - TextJp: バニーの噂
    TextCn: 兔子的传闻
    TextKr: 존재의 이유
    TextEn: ''
    TextTh: ''
    TextTw: ''
    GroupId: 1006703
    FavorScheduleId: 100673
    CharacterId: 10067
    unsure: false
  - TextJp: 心休まる場所
    TextCn: 放松心情的地方
    TextKr: 휴식의 장소
    TextEn: ''
    TextTh: ''
    TextTw: ''
    GroupId: 1006705
    FavorScheduleId: 100675
    CharacterId: 10067
    unsure: false
content:
  - MessageKR: 선생님
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670010
    Id: 100670010
    CharacterId: 10067
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 계십니까?
    MessageJP: いらっしゃいますか？
    MessageCN: 请问您在吗？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670020
    Id: 100670020
    CharacterId: 10067
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670030
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 오, 토키다.
    MessageJP: あれ、トキ？どうしたの？
    MessageCN: 啊，时？怎么了吗？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670030
    Id: 100670030
    CharacterId: 10067
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그렇습니다. 저입니다.
    MessageJP: そうです、私です
    MessageCN: 没错，是我
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670040
    Id: 100670040
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 선생님께 긴히 드리고 싶은 부탁이 있는데, 괜찮으실까요?
    MessageJP: 折り入ってお願いがあるのですが、よろしいでしょうか？
    MessageCN: 有个重要的请求想与您单独谈谈，请问您是否方便？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670040
    Id: 100670050
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 토키의 부탁이라면야, 얼마든지.
    MessageJP: トキのお願いなら何でも聞くよ
    MessageCN: 只要是时的请求我都会听哦
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670050
    Id: 100670060
    CharacterId: 10067
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그 말씀, 확실히 기억했습니다.
    MessageJP: その言葉、ゆめゆめ忘れないでくださいね
    MessageCN: 这番话，请您绝对不要忘记哦
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670060
    Id: 100670070
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670070
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 어…… 잠깐만. 지금 좀 신중하게 생각하고 싶어졌는데……?
    MessageJP: ちょっと待って！一旦、内容聞いてから考えさせて……？
    MessageCN: 等下！姑且让我听一下请求的内容，再让我考虑考虑……？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670070
    Id: 100670080
    CharacterId: 10067
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100672
    NextGroupId: 100670080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 선생님.
    MessageJP: 先生、本日もシャーレにいらっしゃいますよね？
    MessageCN: 老师，今天您也在夏莱对吧？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670080
    Id: 100670090
    CharacterId: 10067
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100670070
    PreConditionFavorScheduleId: 100672
    FavorScheduleId: 0
    NextGroupId: 100670090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그러면 오늘도 실례하겠습니다.
    MessageJP: それでは、本日もお伺い致します。
    MessageCN: 那么，今天我也会前去拜访。
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670090
    Id: 100670100
    CharacterId: 10067
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 괜찮으시지요?
    MessageJP: よろしいですね？
    MessageCN: 没关系吧？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670100
    Id: 100670110
    CharacterId: 10067
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670110
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: ……학생의 방문을 막을 이유는.
    MessageJP: 生徒の訪問を断る理由は……
    MessageCN: 拒绝学生前来访问的理由……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670110
    Id: 100670120
    CharacterId: 10067
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 어떻게 생각해도 없겠지만 말이야……
    MessageJP: どこにも無いからね……
    MessageCN: 世上可没这种东西啊……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670110
    Id: 100670130
    CharacterId: 10067
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 음.
    MessageJP: ふふ
    MessageCN: 呵呵
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670120
    Id: 100670140
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 아무 문제도 없다는 것이로군요.
    MessageJP: そんなに嬉しいのですか？
    MessageCN: 有这么高兴吗？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670130
    Id: 100670150
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 그러면 선생님. 그렇게 알고 있겠습니다.
    MessageJP: でしたら急いで参ります。また、後ほど
    MessageCN: 既然这样那我立刻过来。回头见
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670130
    Id: 100670160
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100673
    NextGroupId: 100670140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 돌입 준비 완료.
    MessageJP: 突入準備完了
    MessageCN: 突破准备完毕
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670140
    Id: 100670170
    CharacterId: 10067
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100670130
    PreConditionFavorScheduleId: 100673
    FavorScheduleId: 0
    NextGroupId: 100670150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 지시를 기다리겠습니다.
    MessageJP: ご指示を
    MessageCN: 请指示
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670150
    Id: 100670180
    CharacterId: 10067
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670160
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 토키……?
    MessageJP: トキ……？
    MessageCN: 时……？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670160
    Id: 100670190
    CharacterId: 10067
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 작전 개시.
    MessageJP: 戦闘開始
    MessageCN: 战斗开始
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670170
    Id: 100670200
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 통신을 일시 차단합니다.
    MessageJP: 通信を遮断します
    MessageCN: 通信切断
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670170
    Id: 100670210
    CharacterId: 10067
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100670180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    unsure: false
  - MessageKR: 토키?!
    MessageJP: トキ！？
    MessageCN: 时！？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
    MessageGroupId: 100670180
    Id: 100670220
    CharacterId: 10067
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100675
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    unsure: false
