CharacterId: 10088
translator: 今天早睡了吗
title:
  - TextJp: 静かなひととき
    TextCn: 宁静的一刻
    TextKr: "늘어져 있는 시간 "
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008802
    FavorScheduleId: 100882
    CharacterId: 10088
  - TextJp: ドレスコード
    TextCn: 着装要求
    TextKr: 분위기에 맞는 옷
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008803
    FavorScheduleId: 100883
    CharacterId: 10088
  - TextJp: 子供の意地
    TextCn: 小孩子的倔强
    TextKr: 어린애의 오기처럼 보이겠지만
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008805
    FavorScheduleId: 100885
    CharacterId: 10088
content:
  - MessageKR: 뭐랄까
    MessageJP: 何というか
    MessageCN: 怎么说呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880010
    Id: 100880010
    CharacterId: 10088
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 예상은 했지만 사람 많은 곳은 피곤하네.
    MessageJP: 予想してたことだけど……この人混みはちょっと疲れるかも
    MessageCN: 虽然我早就想到会这样……但是这么多人还是感觉有点累
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880020
    Id: 100880020
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 일단 해야 할 일은 다 했고…….
    MessageJP: 当面の仕事は終わっているし
    MessageCN: 我也把我该做的工作做完了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880020
    Id: 100880030
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880030
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 잠시 쉬어야겠어.
    MessageJP: ちょっと休もうかな
    MessageCN: 不如稍微休息一下吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880030
    Id: 100880040
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 카요코? 쉰다고?
    MessageJP: カヨコも休憩するの？
    MessageCN: 佳代子也要休息吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880040
    Id: 100880050
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어디 좋은 장소라도 있어?
    MessageJP: どこか良さげな場所でもある？
    MessageCN: 有什么适合休息的地方吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880040
    Id: 100880060
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 후후
    MessageJP: ふふ
    MessageCN: 呵呵
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880050
    Id: 100880070
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생도 지친 모양이네.
    MessageJP: 先生も疲れたんだ
    MessageCN: 老师也累了啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880050
    Id: 100880080
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 뭐
    MessageJP: ……そうだね
    MessageCN: ……这样啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880060
    Id: 100880090
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880070
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 마침 잘 됐나.
    MessageJP: ちょうどいい場所あるよ
    MessageCN: 正好有个合适的地方哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880060
    Id: 100880100
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100882
    NextGroupId: 100880070
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880070
    Id: 100880110
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100880060
    PreConditionFavorScheduleId: 100882
    FavorScheduleId: 0
    NextGroupId: 100880080
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시나 해서 하는 말인데
    MessageJP: 一応、いっておくけど……
    MessageCN: 我，先说一下……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880080
    Id: 100880120
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 필요하면 또 말해
    MessageJP: また必要になったら、いつでも呼んで
    MessageCN: 要是佳代子还有需要的话随时都能叫我
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880090
    Id: 100880130
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 누구한테 말할 생각 없으니 걱정 마
    MessageJP: 大丈夫、みんなには内緒にするから
    MessageCN: 没关系，我会对大家保密的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880090
    Id: 100880140
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응
    MessageJP: うん
    MessageCN: 嗯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880100
    Id: 100880150
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 고마워.
    MessageJP: ありがとう
    MessageCN: 谢谢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880100
    Id: 100880160
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880110
    Id: 100880170
    CharacterId: 10088
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100880100
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 사무실에 들를 일이 있다고 들었는데
    MessageJP: 今日、事務所に来るって言ってたよね
    MessageCN: 您说过今天要来事务所吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880120
    Id: 100880180
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응. 무슨 일 있어?
    MessageJP: うん。何か急な仕事でも入った？
    MessageCN: 嗯。有什么急事吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880130
    Id: 100880190
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아니.
    MessageJP: いや
    MessageCN: 没有
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880140
    Id: 100880200
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880150
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그냥 그 시간대에는 사무실에 사람이 딱히 없을 거라
    MessageJP: ただ、その時間帯だとまだ誰もいないと思うから
    MessageCN: 只是，我觉得大概老师来的时候事务所里还没人
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880140
    Id: 100880210
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아마 내가 맞이하게 될 거 같아서.
    MessageJP: 私が事務所開けておくね
    MessageCN: 我先把事务所门打开吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880150
    Id: 100880220
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼 그 때 봐, 선생.
    MessageJP: じゃあ、待っているね
    MessageCN: 那，我等老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880150
    Id: 100880230
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100883
    NextGroupId: 100880160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880160
    Id: 100880240
    CharacterId: 10088
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100880150
    PreConditionFavorScheduleId: 100883
    FavorScheduleId: 0
    NextGroupId: 100880170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 나중에라도 시간 좀 괜찮을까?
    MessageJP: あとで時間もらえる？
    MessageCN: 我之后能占用您一些时间吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880170
    Id: 100880250
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 카요코?
    MessageJP: カヨコ？
    MessageCN: 佳代子？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880180
    Id: 100880260
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응? 무슨 일이야?
    MessageJP: どうしたの？
    MessageCN: 怎么了？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880180
    Id: 100880270
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아니
    MessageJP: いや
    MessageCN: 没什么
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880190
    Id: 100880280
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 대단한 일은 아니고.
    MessageJP: 大したことじゃないけど
    MessageCN: 不是什么大事
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880190
    Id: 100880290
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이전에 받은 일에 대한 답례 같은 건데.
    MessageJP: この前のお返し、みたいのがしたくて
    MessageCN: 就是我想给老师之前帮过我的事情回个礼
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880200
    Id: 100880300
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아무튼 괜찮은 날이 있으면 언제든 말해줘.
    MessageJP: とにかく、いつでもいいから言って
    MessageCN: 总之，老师什么时候方便了都可以叫我
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880210
    Id: 100880310
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 나머지는 이쪽에서 맞출 테니까.
    MessageJP: こっちで合わせるから
    MessageCN: 我这边会配合老师时间的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880210
    Id: 100880320
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100885
    NextGroupId: 100880220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아
    MessageJP: あ
    MessageCN: 啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880220
    Id: 100880330
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100880210
    PreConditionFavorScheduleId: 100885
    FavorScheduleId: 0
    NextGroupId: 100880230
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 한 가지 잊고 말하지 않은 게 있어
    MessageJP: ひとつ言いそびれたけど
    MessageCN: 有一句话我没说出口
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880230
    Id: 100880340
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음
    MessageJP: うーん
    MessageCN: 唔……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880240
    Id: 100880350
    CharacterId: 10088
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880250
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: ……카요코?
    MessageJP: ……カヨコ？
    MessageCN: ……佳代子？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880250
    Id: 100880360
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880260
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 말하지 않은 거?
    MessageJP: 言いそびれたことって？
    MessageCN: 什么事情没说出口？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880250
    Id: 100880370
    CharacterId: 10088
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880260
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음
    MessageJP: うーん
    MessageCN: 唔……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880260
    Id: 100880380
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880270
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아냐
    MessageJP: やっぱり
    MessageCN: 果然
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880270
    Id: 100880390
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880280
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 역시 지금은 됐어.
    MessageJP: 今はいいかな
    MessageCN: 现在还是算了吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880270
    Id: 100880400
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880280
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 나중에
    MessageJP: あとで
    MessageCN: 之后
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880280
    Id: 100880410
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880290
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 따로 기회가 되면 이야기하지, 뭐.
    MessageJP: 改めて話すから
    MessageCN: 我再说吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880280
    Id: 100880420
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100880290
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼
    MessageJP: じゃあ
    MessageCN: 那
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880290
    Id: 100880430
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 조심해서 돌아가, 선생.
    MessageJP: またね、先生
    MessageCN: 回见啦，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100880290
    Id: 100880440
    CharacterId: 10088
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
