CharacterId: 10081
translator: たかなしち
title:
  - TextJp: 初めてですの！
    TextCn: 初次见面！
    TextKr: 전부 처음 해보는 것이어요!
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008102
    FavorScheduleId: 100812
    CharacterId: 10081
  - TextJp: 駄菓子の味は、えくせれんと！
    TextCn: 粗点心的味道，真是美妙！
    TextKr: 막과자의 맛이 엑설런트이어요!
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008103
    FavorScheduleId: 100813
    CharacterId: 10081
  - TextJp: 休みも大切ですの！
    TextCn: 休息也是很重要的！
    TextKr: 쉬는 것도 중요한 법이어요!
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008105
    FavorScheduleId: 100815
    CharacterId: 10081
  - TextJp: 待ちわびて、楽しみて
    TextCn: 盼望着，期待着
    TextKr: 기다리는 시간조차 즐거이
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008106
    FavorScheduleId: 100816
    CharacterId: 10081
content:
  - MessageKR: 안녕하시어요! 선생님!
    MessageJP: 先生！ごきげんようですの！
    MessageCN: 老师！早上好！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810010
    Id: 100810010
    CharacterId: 10081
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 안녕, 유카리. 오늘도 기운차네.
    MessageJP: おはよう、今日も元気だね
    MessageCN: 早上好，今天也很精神呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810020
    Id: 100810020
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네! 언제나 에너지가 넘치는 것이 저 유카리의 무수히 많은 장점 중 하나이기에!
    MessageJP: ええ！心身共に健康であることが身共の誇れるところですの。ふふん！
    MessageCN: 哎！身心健康可是在下的长处哦。哼！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810030
    Id: 100810030
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810040
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 다만… 이런 모습도 최근엔 선생님 앞에서만 보여드린다고나 할지.
    MessageJP: ですが最近は……先生の前でしか、このようにはしゃぐことはできなくなってきて……
    MessageCN: 但是最近……只有在老师面前，才能这么情绪高涨了……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810030
    Id: 100810040
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810040
    FeedbackTimeMillisec: 2500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 무슨 일 있는 거야?
    MessageJP: 何かあったの？
    MessageCN: 发生什么事了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810040
    Id: 100810050
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그게… 최근 들어 특히나 집안 분위기가 엄격해진 듯해서….
    MessageJP: その……家の言いつけが厳しくなりまして……
    MessageCN: 那个……家里对我的要求越来越严了……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810050
    Id: 100810060
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 카데노코지로서 갖춰야 할 소양을 늘릴 때라고, 공부할 거리가 더 늘어났사와요.
    MessageJP: 勘解由小路家の者として相応しい教養や勉学の指導を受ける日々で……
    MessageCN: 作为勘解由小路家的人，需要接受相应的教养和学习的指导
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810050
    Id: 100810070
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810060
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: "매일 이렇게 공부만 하다간…… "
    MessageJP: "こうも毎日毎日、勉強ばかりでは…… "
    MessageCN: 每天每天都在学习
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810060
    Id: 100810080
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저, 미래엔 왼손으로 주판을 튕기며, 오른손으로는 계산기를 두드리는 공부 귀신이 될 것이 분명하여요!
    MessageJP: 将来は左手で算盤を弾き、右手で電卓を叩く計算の鬼になってしまいますの！
    MessageCN: 将来会成为左手打算盘，右手敲计算器的算数之鬼吧！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810060
    Id: 100810090
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810070
    FeedbackTimeMillisec: 2500
    MessageType: Text
    ImagePath: ""
  - MessageKR: "그 이미지의 출처가 궁금하지만! "
    MessageJP: そんな鬼、聞いたことないよ！？
    MessageCN: 我可没听说过有这样的鬼哦！？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810070
    Id: 100810100
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그래도 역시 한숨 돌리는 건 필요하다고 생각해.
    MessageJP: たまには一息つくのも大事だよ
    MessageCN: 休息的时间也是很重要的哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810080
    Id: 100810110
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 한숨을, 돌린다?
    MessageJP: 一息、つく？
    MessageCN: 休息的时间？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810090
    Id: 100810120
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 한숨을…… 돌리는 행위…… 과연, 흠흠.
    MessageJP: 休める場所で一息を、つく……なるほど、ふむ
    MessageCN: 找个能休息地方好好休息……原来如此，嗯嗯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810090
    Id: 100810130
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저, 유카리 이해한 것이어요!
    MessageJP: 身共、理解しました！
    MessageCN: 在下，领会了！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810100
    Id: 100810140
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼 선생님의 말씀을 받들어… 지금 찾아뵙겠사와요!
    MessageJP: それでは早速、先生のお言葉に甘えて……今からお邪魔しますの！
    MessageCN: 那就恭敬不如从命……我现在就来打扰您了！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810100
    Id: 100810150
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어? 지금 바로……?
    MessageJP: え？今から……？
    MessageCN: 呃？现在就……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810110
    Id: 100810160
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네!
    MessageJP: ええ、今から！
    MessageCN: 嗯，现在！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810120
    Id: 100810170
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100812
    NextGroupId: 100810130
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 최근 식후 디저트를 먹던 도중….
    MessageJP: 先日、食後のでざーとを食べていたら……
    MessageCN: 前几天，我在吃饭后点芯的时候……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810130
    Id: 100810180
    CharacterId: 10081
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100810120
    PreConditionFavorScheduleId: 100812
    FavorScheduleId: 0
    NextGroupId: 100810140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저 유카리, 놀라운 아이디어를 떠올렸사와요!
    MessageJP: すごいことを思いつきましたの！
    MessageCN: 我想到了一个很不错的点子！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810140
    Id: 100810190
    CharacterId: 10081
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좋아. 갑작스러운 이야기지만, 어떤 아이디어야?
    MessageJP: 何を思いついたの？
    MessageCN: 想到什么了？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810150
    Id: 100810200
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: "화과자나 몽블랑, 푸딩처럼. "
    MessageJP: 和菓子やもんぶらん、ぷりんなどなど……
    MessageCN: 日式点心、蒙布朗、布丁等等……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810160
    Id: 100810210
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 디저트에는 단맛의 과자들이 잔뜩이지만!
    MessageJP: でざーとは甘いものばかりですが！
    MessageCN: 这些点心全都是甜的呢！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810160
    Id: 100810220
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 제가 심사숙고해본 결과….
    MessageJP: よく考えてみたら……
    MessageCN: 仔细想想……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810170
    Id: 100810230
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 디저트엔 짠맛도 잘 어울릴 것이라 생각하여요!
    MessageJP: しょっぱい系もいけると思いまして！
    MessageCN: 我觉得咸口也是可以的哦！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810170
    Id: 100810240
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이 기회에 짠맛 디저트를 만들면 소녀도 질리지 않고 마음껏 단짠을…!
    MessageJP: そこで、しょっぱい味のでざーとを作れば、皆様も飽きずに楽しめるのではないかと……！
    MessageCN: 所以我想，如果能做些咸口的甜点的话，大家应该就不会吃腻了吧……！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810180
    Id: 100810250
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810190
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 짠맛 과자라면 이미 많이 있지……?
    MessageJP: 実は……しょっぱい味のお菓子もあるんだ
    MessageCN: 其实……也有咸的点心哦。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810190
    Id: 100810260
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: …네?
    MessageJP: ……え？
    MessageCN: ……欸？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810200
    Id: 100810270
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100813
    NextGroupId: 100810210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님. 다소… 염치가 없지만.
    MessageJP: 先生、急なご連絡で申し訳ありませんが……
    MessageCN: 老师，很抱歉突然联系您……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810210
    Id: 100810280
    CharacterId: 10081
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100810200
    PreConditionFavorScheduleId: 100813
    FavorScheduleId: 0
    NextGroupId: 100810220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 지난번에 이어 오늘도!
    MessageJP: 今日もまた！
    MessageCN: 今天我又！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810220
    Id: 100810290
    CharacterId: 10081
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저 유카리. 많은 것들을 선생님에게 배우고 싶사와요!
    MessageJP: 先生に新しいことを教えていただきたいのです！
    MessageCN: 想要请老师教我新东西了！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810220
    Id: 100810300
    CharacterId: 10081
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좋아. 그럼 나도 샬레에서 기다리고 있을게.
    MessageJP: もちろん！それじゃあ、シャーレで待ってるね
    MessageCN: 当然！那我在夏莱里等你。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810230
    Id: 100810310
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810240
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네! 바로 가겠사와요!
    MessageJP: はい！すぐに向かいますの！
    MessageCN: 好的！我马上就过去！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810240
    Id: 100810320
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100815
    NextGroupId: 100810250
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님, 빅- 뉴스여요!
    MessageJP: 先生、びっぐにゅーすですの！
    MessageCN: 老师，有大新闻！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810250
    Id: 100810330
    CharacterId: 10081
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 100810240
    PreConditionFavorScheduleId: 100815
    FavorScheduleId: 0
    NextGroupId: 100810260
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘 백귀야행 제7번 상점가에서 <추첨식>이라는 특별한 이벤트를 한다고 들었사와요!
    MessageJP: 今日、百鬼夜行第七商店街で「抽選会」が行われると聞きまして！
    MessageCN: 听说今天在百鬼夜行第七商店街有“抽奖”！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810260
    Id: 100810340
    CharacterId: 10081
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810270
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아, 상점가에서 자주 하는 그거 말이구나.
    MessageJP: 商店街でよくやってるやつだね
    MessageCN: 商店街经常会办的活动呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810270
    Id: 100810350
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810280
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 상품 중에는 오딧세이아 해양학교의 휴양지로 떠날 수 있는 초대권도 있다는 모양이어요.
    MessageJP: 商品の中には、おでゅっせいあ海洋高等学校のりぞーとに行ける招待券もあるみたいですのよ
    MessageCN: 商品中好像有可以去奥德赛海洋高等学校的招待券。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810280
    Id: 100810360
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810290
    FeedbackTimeMillisec: 2500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 꽤 호화스럽네.
    MessageJP: そんなに豪華な景品もあるんだ
    MessageCN: 还有怎么豪华的奖品啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810290
    Id: 100810370
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810300
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아, 그럼 이럴 게 아니라.
    MessageJP: ええ！
    MessageCN: 是的！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810300
    Id: 100810380
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810310
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님!
    MessageJP: それで、その……
    MessageCN: 所以说，那个……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810300
    Id: 100810390
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810310
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응. 가볼까?
    MessageJP: うん、一緒に行こうか
    MessageCN: 嗯，一起去吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810310
    Id: 100810400
    CharacterId: 10081
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100810320
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네! 그럼 평소처럼 그곳에서!
    MessageJP: はい！いつもの場所でお待ちしておりますの！
    MessageCN: 好的！我在老地方等你！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100810320
    Id: 100810410
    CharacterId: 10081
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100816
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
