CharacterId: 10086
translator: 今天早睡了吗
title:
  - TextJp: ヒナとドレス（１）
    TextCn: 日奈与礼服（1）
    TextKr: ""
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008602
    FavorScheduleId: 100862
    CharacterId: 10086
  - TextJp: ヒナとドレス（２）
    TextCn: 日奈与礼服（2）
    TextKr: ""
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008603
    FavorScheduleId: 100863
    CharacterId: 10086
  - TextJp: ヒナとピアノ
    TextCn: 日奈与钢琴
    TextKr: ""
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1008605
    FavorScheduleId: 100865
    CharacterId: 10086
content:
  - MessageKR: 선생님. 조금 업무 관련으로 상담하고 싶은 게 있는데.
    MessageJP: 先生、少し相談があるのだけど
    MessageCN: 老师，我有点事情想和您商量
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860010
    Id: 100860010
    CharacterId: 10086
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좋아, 샬레 출동이다!
    MessageJP: よし、今すぐ出動だ！
    MessageCN: 好，我现在马上出动！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860020
    Id: 100860020
    CharacterId: 10086
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 으, 응? 출동…?
    MessageJP: う、うん？出動……？
    MessageCN: 嗯、嗯？出动……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860030
    Id: 100860030
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어디서 만날까? 히나.
    MessageJP: どこに行けばいい？
    MessageCN: 我要去哪？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860040
    Id: 100860040
    CharacterId: 10086
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아, 응. 출동이란 게, 바로 만나자는 의미였구나.
    MessageJP: 出動って、会いに来てくれるって意味だったの？
    MessageCN: 老师说的“出动”是说要过来见我吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860050
    Id: 100860050
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: …후훗. 선생님답네.
    MessageJP: ふふっ、先生らしいね
    MessageCN: 呵呵，很有老师的风格呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860060
    Id: 100860060
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘은 내가 샬레로 찾아갈게.
    MessageJP: 今日は私がシャーレに行くわ
    MessageCN: 我今天会去夏莱哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860070
    Id: 100860070
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼 조금 이따가 보자. 선생님.
    MessageJP: じゃあ後でね、先生
    MessageCN: 那待会见啦，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860070
    Id: 100860080
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100862
    NextGroupId: 100860080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님, 저번에 이야기했던 약속 말인데….
    MessageJP: 先生、この間の約束だけど……
    MessageCN: 老师，我们上次好像约好过……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860080
    Id: 100860090
    CharacterId: 10086
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100860070
    PreConditionFavorScheduleId: 100862
    FavorScheduleId: 0
    NextGroupId: 100860090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응, 이번 휴일에 히나의 드레스를 사러 가기로 했었지!
    MessageJP: うん、ドレスを買いに行くんだよね！
    MessageCN: 嗯，是要去买礼服对吧！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860090
    Id: 100860100
    CharacterId: 10086
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 히나와 쇼핑할 날만 기다리고 있었으니까!
    MessageJP: ショッピング、楽しみだね！
    MessageCN: 我很期待购物哦！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860090
    Id: 100860110
    CharacterId: 10086
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 후후… 그렇게까지 의욕을 내서 말해주다니, 고마워.
    MessageJP: ふふ……そんなに張り切ってもらえるなんて、嬉しい
    MessageCN: 呵呵……老师居然对我的事这么上心，我很开心
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860100
    Id: 100860120
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그래서 그 드레스를 사러 가는 장소와 관련해서.
    MessageJP: それで、ドレスを買う場所なのだけど
    MessageCN: 然后，就是买礼服的地方
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860110
    Id: 100860130
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아무래도 우리 선도부는 만마전이나 여러 문제아들처럼. 악감정을 가진 학생들이 많거든.
    MessageJP: ゲヘナには、風紀委員をあまり良く思っていない人たちも多いでしょう
    MessageCN: 在格黑娜，应该有很多人都不会给风纪委员好脸色看吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860110
    Id: 100860140
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 때문에 게헨나의 쇼핑몰을 방문하면 여러모로 문제가 생길지도 몰라.
    MessageJP: こっちのショッピングモールだと、落ち着いて買い物できないかもしれなくて……
    MessageCN: 在这里的购物中心买的话，可能就不能安心买东西了……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860120
    Id: 100860150
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그러니….
    MessageJP: だから……
    MessageCN: 所以……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860130
    Id: 100860160
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860140
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 게헨나 자치구 외곽에서 보자는 거지? 알았어.
    MessageJP: なら、ゲヘナの外で見よっか？
    MessageCN: 那，去格黑娜外面找找看吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860140
    Id: 100860170
    CharacterId: 10086
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응. 그럼 장소의 주소를 보내줄게.
    MessageJP: うん、待ち合わせ場所は送っておくわ
    MessageCN: 嗯，那我把碰头地点发给老师吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860150
    Id: 100860180
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그곳에서 보자. 선생님.
    MessageJP: 待ってるね、先生
    MessageCN: 我等着您哦，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860150
    Id: 100860190
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100863
    NextGroupId: 100860160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님. 내일 시간이 있을까?
    MessageJP: 先生、明日は空いてる？
    MessageCN: 老师明天有时间吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860160
    Id: 100860200
    CharacterId: 10086
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100860150
    PreConditionFavorScheduleId: 100863
    FavorScheduleId: 0
    NextGroupId: 100860170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이번 게헨나 파티에서 연주가 끝난 만큼, 조금 일정에 여유가 생긴 참에…….
    MessageJP: ゲヘナのパーティーが終わったから、少し余裕ができて
    MessageCN: 格黑娜的宴会结束之后，我也有点空闲时间了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860170
    Id: 100860210
    CharacterId: 10086
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 괜찮다면 내일 선생님과 만나고 싶은데.
    MessageJP: 良かったら、先生に会いたいのだけど……
    MessageCN: 如果可以的话，我想和老师见一面……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860180
    Id: 100860220
    CharacterId: 10086
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 히나의 일정에 여유가 생기다니. 엄청 드문 일이네!
    MessageJP: ヒナの予定が空くなんて珍しいね！
    MessageCN: 日奈居然有空出来的时间，真少见呢！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860190
    Id: 100860230
    CharacterId: 10086
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그 귀중한 기회를 놓칠 수 없지! 바로 갈게!
    MessageJP: 絶対、会いに行くよ！
    MessageCN: 我一定会去的！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860190
    Id: 100860240
    CharacterId: 10086
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 후후, 또 선생님답게 야단이라니까.
    MessageJP: ふふ、大げさね
    MessageCN: 呵呵，老师这也太夸张了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860200
    Id: 100860250
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100860210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼 내일, 파티홀에서 기다리고 있을게.
    MessageJP: じゃあ、パーティー会場で待ってるわ
    MessageCN: 那，我在晚会现场等老师吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100860210
    Id: 100860260
    CharacterId: 10086
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100865
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
