CharacterId: 10096
translator: Azenix
title:
  - TextJp: 水着選び
    TextCn: 选泳装
    TextKr: 수영복을 고르자
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1009602
    FavorScheduleId: 100962
    CharacterId: 10096
  - TextJp: 試運転
    TextCn: 试运行
    TextKr: 워터슬라이드 점검
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1009603
    FavorScheduleId: 100963
    CharacterId: 10096
  - TextJp: ライフセーバーの特権
    TextCn: 救生员的特权
    TextKr: 라이프가드의 특권
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1009605
    FavorScheduleId: 100965
    CharacterId: 10096
content:
  - MessageKR: 안녕하십니까, 선생님. 칸나입니다.
    MessageJP: こんにちは、先生
    MessageCN: 您好，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960010
    Id: 100960010
    CharacterId: 10096
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오랜만이네, 칸나.
    MessageJP: 久しぶりだね、カンナ
    MessageCN: 好久不见啊，康娜
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960020
    Id: 100960020
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그동안 잘 지냈어?
    MessageJP: 元気だった？
    MessageCN: 最近过的怎么样？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960020
    Id: 100960030
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 갑작스럽게 연락드려 죄송하지만, 상담하고 싶은 것이 생겼습니다.
    MessageJP: お久しぶりです。実は、相談したいことがありまして
    MessageCN: 好久不见了，老师。其实我有件事想跟您商量一下……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960030
    Id: 100960040
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 칸나의 상담이라, 드문 일인걸.
    MessageJP: カンナから相談だなんて、珍しいね
    MessageCN: 康娜居然想找我商量事情，还挺少见的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960040
    Id: 100960050
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 다름이 아니라, 이번에 라이프가드 임무를 맡게 되었습니다.
    MessageJP: その、プールのライフセーバーに任命されたのですが……
    MessageCN: 那个，其实我被任命成了泳池救生员……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960050
    Id: 100960060
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 한데, 수영복에 문제가 있어서…….
    MessageJP: 水着が決められずに困っています
    MessageCN: 但是，我到现在还在头疼该穿什么泳衣……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960050
    Id: 100960070
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 문제?
    MessageJP: ……水着？
    MessageCN: ……泳衣？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960060
    Id: 100960080
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그게……혹시 괜찮으시다면 직접 뵙고 조언을 부탁드려도 될까요?
    MessageJP: はい、よろしければ直接アドバイスを頂いてもよろしいでしょうか？
    MessageCN: 是的，如果老师方便的话可以直接给点建议吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960070
    Id: 100960090
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960080
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저 혼자 결정하기에는 어딘가 마음이 편치 않습니다.
    MessageJP: 私には、どうも難しく……
    MessageCN: 这种事情对我来说有点太难了……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960080
    Id: 100960100
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론이지, 금방 갈게.
    MessageJP: 分かった、すぐ行くね
    MessageCN: 知道了，我马上过去
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960090
    Id: 100960110
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100962
    NextGroupId: 100960100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 잘 들어가셨습니까? 오늘은 감사했습니다, 선생님.
    MessageJP: 先生、本日はありがとうございました
    MessageCN: 今天真的非常感谢老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960100
    Id: 100960120
    CharacterId: 10096
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100960090
    PreConditionFavorScheduleId: 100962
    FavorScheduleId: 0
    NextGroupId: 100960110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 덕분에 좋은 수영복을 고를 수 있었습니다.
    MessageJP: おかげで水着が決まり、一安心です
    MessageCN: 多亏有老师，我的泳衣终于选好了，这下我就放心了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960110
    Id: 100960130
    CharacterId: 10096
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 칸나가 마음에 든다면 다행이야.
    MessageJP: 似合ってたね
    MessageCN: 那件泳衣，很适合你哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960120
    Id: 100960140
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: …….
    MessageJP: ……
    MessageCN: ……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960130
    Id: 100960150
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 사실, 아까 한 가지 깨달았습니다.
    MessageJP: 今さらですが、気付いたのです
    MessageCN: 事到如今我才意识到
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960130
    Id: 100960160
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어쩌면 저는, 누군가의 ‘잘 어울린다’는 말 한마디가 필요했던 것인지도 모르겠습니다.
    MessageJP: もしかしたら私には、「似合っている」の一言が必要だっただけかもしれません
    MessageCN: 也许对我来说，我需要的可能只是一句“很适合你”吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960140
    Id: 100960170
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 처음 해 보는 임무인지라 안심이 되지 않았으니까요.
    MessageJP: 初めてのライフセーバー任務で、気負いすぎていたのでしょう
    MessageCN: 可能因为我是第一次当救生员，有点逞强了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960150
    Id: 100960180
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 잘됐네. 이제 좀 마음을 놓았어?
    MessageJP: もう気は楽になった？
    MessageCN: 现在感觉轻松多了吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960160
    Id: 100960190
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네, 그렇습니다.
    MessageJP: はい
    MessageCN: 是的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960170
    Id: 100960200
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 역시, 선생님께 도움을 요청한 것이 정답이었군요
    MessageJP: やはり、先生に助けを要請して正解でした
    MessageCN: 果然，选择向老师求助是正确的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960170
    Id: 100960210
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 안녕하십니까, 선생님.
    MessageJP: こんにちは、先生
    MessageCN: 您好，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960180
    Id: 100960220
    CharacterId: 10096
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100960170
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 파크는 잘 즐기고 계신지 모르겠군요.
    MessageJP: パークは楽しめていますか？
    MessageCN: 在水上乐园玩的开心吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960190
    Id: 100960230
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응, 들어오자마자 물놀이 중이야.
    MessageJP: うん、楽しんでるよ
    MessageCN: 嗯，我玩得很开心哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960200
    Id: 100960240
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 즐겨 주시는 것 같아 라이프가드로서 기쁘군요.
    MessageJP: ライフセーバーとして、嬉しい限りです
    MessageCN: 作为一名救生员，听到您说这句话我很开心
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960210
    Id: 100960250
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저, 혹시 실례가 되지 않는다면, 한 가지 부탁을 드리고 싶습니다.
    MessageJP: あの、もしお時間があれば、ひとつお願いをしても良いでしょうか？
    MessageCN: 那个，如果您有空的话，能拜托您一件事吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960210
    Id: 100960260
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 무슨 부탁인데?
    MessageJP: どんなお願い？
    MessageCN: 要我帮什么忙？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960220
    Id: 100960270
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960230
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 실외 시설에 있는 ‘메가 슬라이드’로 와 주시겠습니까?
    MessageJP: 屋外施設の「メガスライド」まで来てもらえませんか？
    MessageCN: 老师能来室外项目的“超级水上滑梯”这边一趟吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960230
    Id: 100960280
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 운행 시작 전에 시험 운행을 부탁드리고 싶습니다.
    MessageJP: 試運転に付き合っていただきたいのです
    MessageCN: 我想请您陪我一起测试这个设施的运转情况
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960230
    Id: 100960290
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100963
    NextGroupId: 100960240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘은 워터파크가 운영하지 않는 날입니다.
    MessageJP: 今日はウォーターパークの定休日です
    MessageCN: 今天是水上乐园的休息日
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960240
    Id: 100960300
    CharacterId: 10096
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100960230
    PreConditionFavorScheduleId: 100963
    FavorScheduleId: 0
    NextGroupId: 100960250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시나 요일을 혼동하여 방문하지 않도록 주의해 주시기 바랍니다.
    MessageJP: 間違えないよう、お気をつけてください
    MessageCN: 请您注意不要弄错时间
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960250
    Id: 100960310
    CharacterId: 10096
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼 칸나도 쉬는 거야?
    MessageJP: じゃあカンナも休みなの？
    MessageCN: 那康娜今天也休息吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960260
    Id: 100960320
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960270
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그렇지는 않습니다.
    MessageJP: いえ、私は仕事です
    MessageCN: 不，我今天上班
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960270
    Id: 100960330
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960280
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 라이프가드들은 시설의 관리보수와 청소를 해야 하니까요.
    MessageJP: 施設の清掃や補修がありますから
    MessageCN: 因为游乐设施还需要清洁和维护
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960270
    Id: 100960340
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960280
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이용객 여러분이 안전하고 즐겁게 시설을 이용할 수 있도록 최선을 다할 생각입니다.
    MessageJP: 利用客の皆さんが、安全に楽しく遊べるようにしなくてはいけませんので
    MessageCN: 我们必须保证每一位游客都能安全快乐地游玩
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960280
    Id: 100960350
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960290
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 휴일이 휴일이 아니구나…….
    MessageJP: 定休日なのに大変だね……
    MessageCN: 休息日还要上班，真辛苦啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960290
    Id: 100960360
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960300
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 너무 열심히 하는 거 아냐?
    MessageJP: 少し頑張りすぎじゃない？
    MessageCN: 是不是有点太拼了？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960290
    Id: 100960370
    CharacterId: 10096
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960300
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이용객의 안전을 책임지는 라이프가드로서 당연한 일입니다.
    MessageJP: 利用客の安全がかかっておりますし、これくらい当然です
    MessageCN: 这是我们应该做的，毕竟事关游客安全
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960300
    Id: 100960380
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100960310
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 또한, 그 이용객에는 선생님도 포함되어 있으니까요.
    MessageJP: もちろん、そこには先生も含まれていますから
    MessageCN: 当然，其中也包括老师您
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100960310
    Id: 100960390
    CharacterId: 10096
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100965
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
