CharacterId: 10098
translator: Sino
title:
  - TextJp: ヒーロー、誕生
    TextCn: 英雄，诞生
    TextKr: 히어로, 탄생
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1009802
    FavorScheduleId: 100982
    CharacterId: 10098
  - TextJp: ヒーロー、パトロール
    TextCn: 英雄，巡逻
    TextKr: 히어로, 순찰
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1009803
    FavorScheduleId: 100983
    CharacterId: 10098
  - TextJp: ヒーロー、決戦
    TextCn: 英雄，决战
    TextKr: 히어로, 결전
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1009805
    FavorScheduleId: 100985
    CharacterId: 10098
content:
  - MessageKR: 선생
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980010
    Id: 100980010
    CharacterId: 10098
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 바빠?
    MessageJP: 今って忙しい？
    MessageCN: 您现在忙吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980020
    Id: 100980020
    CharacterId: 10098
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 평소대로인걸.
    MessageJP: そこまで忙しくないよ
    MessageCN: 没那么忙哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980030
    Id: 100980030
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그게
    MessageJP: 良かった
    MessageCN: 那太好了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980040
    Id: 100980040
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980050
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 곤란한 일이 생겼는데 말이지
    MessageJP: 実は困ったことがあってね
    MessageCN: 其实我遇到了一件棘手的事
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980040
    Id: 100980050
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생이 조금 도와줬으면 한달까.
    MessageJP: ちょっと手伝ってほしいんだ
    MessageCN: 想请您帮帮忙
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980050
    Id: 100980060
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론 도와줘야지.
    MessageJP: うん、良いよ
    MessageCN: 嗯，好啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980060
    Id: 100980070
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응?
    MessageJP: 本当に良いの？
    MessageCN: 真的可以吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980070
    Id: 100980080
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980080
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아직 무슨 일인지 말 안 했는데?
    MessageJP: まだ内容も言ってないのに……
    MessageCN: 我还没说是什么事呢……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980070
    Id: 100980090
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100982
    NextGroupId: 100980080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘은 자치구 순찰 예정인데
    MessageJP: これから自治区のパトロールをするんだけど
    MessageCN: 大叔我接下来要去自治区巡逻
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980080
    Id: 100980100
    CharacterId: 10098
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 100980070
    PreConditionFavorScheduleId: 100982
    FavorScheduleId: 0
    NextGroupId: 100980090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 선생도 갈 생각이 있다면
    MessageJP: よかったら先生もどう？
    MessageCN: 如果方便的话，老师也一起去怎么样？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980090
    Id: 100980110
    CharacterId: 10098
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론 동행해야지!
    MessageJP: もちろん同行するよ！
    MessageCN: 当然要去！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980100
    Id: 100980120
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아비도스 히어로가 가는데 빠질 순 없잖아?
    MessageJP: ヒーローの頼みとあれば！
    MessageCN: 英雄的请求我都会听的！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980110
    Id: 100980130
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 으으
    MessageJP: うぅ
    MessageCN: 呜呜
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980120
    Id: 100980140
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980130
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 히어로라니
    MessageJP: ヒーローだなんて
    MessageCN: 英雄什么的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980120
    Id: 100980150
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 역시 적응 안 되네…….
    MessageJP: やっぱり恥ずかしいねぇ
    MessageCN: 果然好羞耻啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980130
    Id: 100980160
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아무튼 기다릴게~
    MessageJP: まあ、とにかく待ってるよ～
    MessageCN: 总之，等着您哦～
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980140
    Id: 100980170
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100983
    NextGroupId: 100980150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980150
    Id: 100980180
    CharacterId: 10098
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 100980140
    PreConditionFavorScheduleId: 100983
    FavorScheduleId: 0
    NextGroupId: 100980160
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 컨디션은 괜찮아?
    MessageJP: 体調はどう？
    MessageCN: 身体怎么样？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980160
    Id: 100980190
    CharacterId: 10098
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 감기 기운은 없고?
    MessageJP: 風邪とか引いてない？
    MessageCN: 有没有感冒之类的？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980160
    Id: 100980200
    CharacterId: 10098
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 난 괜찮아. 호시노는 어때? 괜찮아?
    MessageJP: 私は大丈夫、ホシノは？
    MessageCN: 我没事，星野呢？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980170
    Id: 100980210
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이 아저씨는 끄떡없다구
    MessageJP: おじさんも元気だよ～
    MessageCN: 大叔我也没问题哦～
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980180
    Id: 100980220
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 역시 밤새 꼭 붙어 있었던 덕분인가.
    MessageJP: やっぱり、一晩中くっついてたおかげかな？
    MessageCN: 果然是整晚都紧贴在一起的功劳吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980190
    Id: 100980230
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아ㅣㄴ그건
    MessageJP: わっ
    MessageCN: 哇
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980200
    Id: 100980240
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980210
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아니 그건
    MessageJP: いや
    MessageCN: 紧贴什么的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980210
    Id: 100980250
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980220
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 나란히 앉아서 모포를 뒤집어쓴 것 뿐이니까
    MessageJP: 一緒の毛布に包まってただけだから！
    MessageCN: 只是同盖一床毛毯而已哦！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980220
    Id: 100980260
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오해 살 수 있는 발언은 금지!
    MessageJP: その言い方だと誤解されるじゃん！
    MessageCN: 那样说话不是会被误解的吗！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980220
    Id: 100980270
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음
    MessageJP: ……それとさ
    MessageCN: ……再说啦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980230
    Id: 100980280
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980240
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그리고
    MessageJP: 昨日、自治区で一緒に人助けしたでしょ？
    MessageCN: 昨天，我们不是一起在自治区帮助大家了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980240
    Id: 100980290
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980250
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어제 자치구를 돌아다니면서 사람들 도와준 거
    MessageJP: 昔、似たようなことをしたことがあってね
    MessageCN: 以前我也做过类似的事呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980240
    Id: 100980300
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980250
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 다른 사람이랑도 이런 일 했었거든
    MessageJP: ちょっと、懐かしい気分になったんだ
    MessageCN: 稍微有点怀念的感觉
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980250
    Id: 100980310
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생 덕분에 오랜만에 그리운 감각을 느꼈달까
    MessageJP: その、だからさ……
    MessageCN: 那个，所以说啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980250
    Id: 100980320
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980260
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아무튼 여러가지로
    MessageJP: うん、とにかくありがとう
    MessageCN: 嗯，总之谢谢您了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980260
    Id: 100980330
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980270
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 고마워
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980260
    Id: 100980340
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980270
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저번 순찰 기억해, 선생?
    MessageJP: 先生、この前のパトロールは覚えてる？
    MessageCN: 老师，还记得上次巡逻的事吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980270
    Id: 100980350
    CharacterId: 10098
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 100980260
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980280
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론이지.
    MessageJP: もちろん
    MessageCN: 当然
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980280
    Id: 100980360
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980290
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 꽤 오랫동안 돌아다녔는데
    MessageJP: 結構いろんな場所を見て回ってたじゃん？
    MessageCN: 我们不是去了挺多地方的吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980290
    Id: 100980370
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980300
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 정작 헬멧단은 못 봤잖아?
    MessageJP: でも、ヘルメット団の痕跡は見つからなかったよね
    MessageCN: 不过，还是没有发现钢盔团的痕迹呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980290
    Id: 100980380
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980300
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그러고 보니 그렇네?
    MessageJP: たしかに……
    MessageCN: 确实……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980300
    Id: 100980390
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980310
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 녀석들이 어디 있나 했는데
    MessageJP: あれから調べてみたらさ
    MessageCN: 后来我调查了一下
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980310
    Id: 100980400
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980320
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 요즘 상점가 근처에 자주 나타난다는 소문이 있어
    MessageJP: 商店街の近くで、よく見かけたっていう情報を手に入れたんだ
    MessageCN: 得到情报说在商店街附近经常看到她们呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980310
    Id: 100980410
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980320
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 임시 아지트가 그쪽에 있나 봐.
    MessageJP: たぶん、その周辺にアジトがあるはず
    MessageCN: 那附近应该有她们的据点
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980320
    Id: 100980420
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980330
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 준비됐어, 히어로?
    MessageJP: ヒーローの準備はできてる？
    MessageCN: 英雄做好准备了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980330
    Id: 100980430
    CharacterId: 10098
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 100980340
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론이지, 사이드킥.
    MessageJP: うへへ。もちろんだよ、相棒
    MessageCN: 呜嘿嘿。当然啦，搭档。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 100980340
    Id: 100980440
    CharacterId: 10098
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 100985
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
