CharacterId: 10101
translator: Soraの天空
title:
  - TextKr: 식당 아르바이트
    TextJp: 食堂アルバイト
    TextCn: 食堂打工
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1010102
    FavorScheduleId: 101012
    CharacterId: 10101
    unsure: false
  - TextKr: 축제의 소리를 찾아서
    TextJp: お祭りの音を探して
    TextCn: 寻找祭典的声音
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1010103
    FavorScheduleId: 101013
    CharacterId: 10101
    unsure: false
  - TextKr: 둘만의 뒷풀이
    TextJp: 二人だけの打ち上げ
    TextCn: 只属于两人的庆功宴
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1010105
    FavorScheduleId: 101015
    CharacterId: 10101
    unsure: false
content:
  - MessageKR: 선생.
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010010
    Id: 101010010
    CharacterId: 10101
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 축제는 즐기고 있는지 모르겠군.
    MessageJP: お祭りは楽しんでいるか
    MessageCN: 祭典玩得开心吗
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010020
    Id: 101010020
    CharacterId: 10101
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 앗, 사오리.
    MessageJP: もちろんだよ、サオリ
    MessageCN: 当然啦，沙织
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010030
    Id: 101010030
    CharacterId: 10101
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 물론, 즐기고 있지.
    MessageJP: 楽しめてるよ
    MessageCN: 我十分享受哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010030
    Id: 101010040
    CharacterId: 10101
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 다행이군.
    MessageJP: それは良かった
    MessageCN: 那就太好了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010040
    Id: 101010050
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 나는 해변 구역의 식당에서 업무를 시작한 참이다.
    MessageJP: 私は海辺の食堂でアルバイトを始めたところだ
    MessageCN: 我最近开始在海边的食堂打工
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010040
    Id: 101010060
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생도 배가 고프면 와도 괜찮다.
    MessageJP: お腹が空いたら、ぜひ先生も来てくれ
    MessageCN: 如果老师您肚子饿了，欢迎前来就餐
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010050
    Id: 101010070
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101012
    NextGroupId: 101010060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생, 저번 일은 고마웠다.
    MessageJP: 先生、この間は世話になった
    MessageCN: 老师，前段时间承蒙您关照了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010060
    Id: 101010080
    CharacterId: 10101
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 101010050
    PreConditionFavorScheduleId: 101012
    FavorScheduleId: 0
    NextGroupId: 101010070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘은 다른 일이 생겨서, 축제장을 조금 둘러볼 생각이다.
    MessageJP: 今日は会場の見回りをするんだが、一人では手が足りなそうでな……
    MessageCN: 今天我要巡视会场，可一个人实在力不从心……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010070
    Id: 101010090
    CharacterId: 10101
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 혼자서는 조금 힘들 것 같아서, 도움을 요청하고 싶다만…….
    MessageJP: よければ先生の力を借りられないだろうか？
    MessageCN: 如果方便的话，能否请您前来搭把手呢？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010070
    Id: 101010100
    CharacterId: 10101
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010080
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 물론, 나는 환영이지.
    MessageJP: もちろん、手伝うよ
    MessageCN: 当然，我会来帮忙的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010080
    Id: 101010110
    CharacterId: 10101
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 고맙다. 그럼, 축제장 입구에서 기다리겠다.
    MessageJP: 感謝する。では、会場の入口で待ち合わせしよう
    MessageCN: 谢谢。那么我们在会场的入口会合吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010090
    Id: 101010120
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101013
    NextGroupId: 101010100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생, 오늘 수집한 소리 샘플들을 시험해 봤다.
    MessageJP: 先生、さっき録音した音を加工してみた
    MessageCN: 老师，我试着加工了下刚才录下的素材
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010100
    Id: 101010130
    CharacterId: 10101
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 101010090
    PreConditionFavorScheduleId: 101013
    FavorScheduleId: 0
    NextGroupId: 101010110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 다행히 괜찮은 작품이 나올 것 같아.
    MessageJP: 中々良い出来かもしれない
    MessageCN: 感觉效果相当好
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010110
    Id: 101010140
    CharacterId: 10101
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그거 잘 됐네!
    MessageJP: 良かった！
    MessageCN: 太好了！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010120
    Id: 101010150
    CharacterId: 10101
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 어디
    MessageJP: 先生にもデータを送るから、聞いてみてくれ
    MessageCN: 我给您也发送了一份，请听听看
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010130
    Id: 101010160
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: (파일 전송에 실패하였습니다.)
    MessageJP: （ファイルの送信に失敗しました）
    MessageCN: （文件发送失败）
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010140
    Id: 101010170
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010150
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 아
    MessageJP: あ
    MessageCN: 哎呀
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010150
    Id: 101010180
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 이런
    MessageJP: そうか
    MessageCN: 这样呀
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010150
    Id: 101010190
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 용량 문제인가…….
    MessageJP: 容量のせいで……
    MessageCN: 是文件大小的缘故……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010160
    Id: 101010200
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 공연장에 직접 가서 듣는 것으로 할게.
    MessageJP: 会場で直接聞くね
    MessageCN: 我会直接在会场听的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010170
    Id: 101010210
    CharacterId: 10101
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 으음, 그래 주면 고맙겠다…….
    MessageJP: あぁ、分かった
    MessageCN: 好的，我知道了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010180
    Id: 101010220
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010190
    Id: 101010230
    CharacterId: 10101
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 101010180
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘 저녁에 DJ공연이 예정되어 있다.
    MessageJP: 今日の夕方からDJステージがあるんだが
    MessageCN: 今天从傍晚起会有DJ演出
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010200
    Id: 101010240
    CharacterId: 10101
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 괜찮다면 보러 오지 않겠나?
    MessageJP: 良かったら見に来てくれないか？
    MessageCN: 方便的话可以来看看吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010200
    Id: 101010250
    CharacterId: 10101
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 응, 꼭 갈게.
    MessageJP: うん、絶対に行くよ
    MessageCN: 嗯，我一定会去的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010210
    Id: 101010260
    CharacterId: 10101
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 고맙다. 시간은 해가 진 뒤, 장소는 축제장 메인 스테이지다.
    MessageJP: 日が沈んでから、メインステージで始まる予定だ
    MessageCN: 演出应该会在太阳落山后在主舞台开始
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010220
    Id: 101010270
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101010230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 기다리고 있겠다.
    MessageJP: では、待っている
    MessageCN: 那么，我等着您
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101010230
    Id: 101010280
    CharacterId: 10101
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101015
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
