CharacterId: 10103
translator: Sino
title:
  - TextJp: 嘘と真
    TextCn: 虚与实
    TextKr: 허풍과 진실
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1010302
    FavorScheduleId: 101032
    CharacterId: 10103
  - TextJp: 羞花閉月
    TextCn: 闭月羞花
    TextKr: 입 다물면 미인
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1010303
    FavorScheduleId: 101033
    CharacterId: 10103
  - TextJp: 快刀乱麻
    TextCn: 快刀乱麻
    TextKr: 쾌도난마
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1010305
    FavorScheduleId: 101035
    CharacterId: 10103
content:
  - MessageKR: 선생……?
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030010
    Id: 101030010
    CharacterId: 10103
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오. 마리나다. 무슨 일이야?
    MessageJP: マリナ、どうしたの？
    MessageCN: 玛丽娜，怎么了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030020
    Id: 101030020
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 지금, 산해경의 현무상회라는 곳에 와 있는데.
    MessageJP: 山海経の玄武商会というところに来ているんだが
    MessageCN: 我来到了山海经一个叫玄武商会的地方
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030030
    Id: 101030030
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 약간 당혹스러운 일이 생겨서 말이다.
    MessageJP: 少し困っていてな
    MessageCN: 遇到了一点麻烦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030030
    Id: 101030040
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 민망하지만, 조금, 도움을 청하고 싶어서…….
    MessageJP: 良ければ助けてもらえないか？
    MessageCN: 方便过来帮我吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030040
    Id: 101030050
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: "금방 갈게! "
    MessageJP: すぐ行くね
    MessageCN: 我马上过去
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030050
    Id: 101030060
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101032
    NextGroupId: 101030060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 과식한 탓인가…….
    MessageJP: 食べ過ぎたせいか
    MessageCN: 好像吃太多了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030060
    Id: 101030070
    CharacterId: 10103
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 101030050
    PreConditionFavorScheduleId: 101032
    FavorScheduleId: 0
    NextGroupId: 101030070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 뭔가, 배가 아픈 것 같군……
    MessageJP: 少し、お腹が……
    MessageCN: 肚子有点……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030070
    Id: 101030080
    CharacterId: 10103
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: ……괜찮아?
    MessageJP: ……大丈夫？
    MessageCN: ……没事吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030080
    Id: 101030090
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 한 가지는 확실하게 배운 것 같다.
    MessageJP: ああ、ひとつ確実な学びを得たぞ
    MessageCN: 没事，不过我确实学到了一件事
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030090
    Id: 101030100
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음식의 겉모양이, 반드시 맛과 일치하지 않는다는 것을.
    MessageJP: 食べ物の味と見た目は、必ずしも一致しないようだ
    MessageCN: 食物的味道和外观不一定一致
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030090
    Id: 101030110
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그 벌레 꼬치 말인데, 관광객한테만 파는 거래.
    MessageJP: 実は、あの虫の串焼きって観光客向けなんだけど……
    MessageCN: 其实，那些烤虫子基本都是卖给游客吃的……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030100
    Id: 101030120
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 왜 그런 말을 지금 해 주는 건가!
    MessageJP: それならそうと早く言ってくれ！
    MessageCN: 那你早说啊！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030110
    Id: 101030130
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어디까지 왔지?
    MessageJP: 着いたぞ、先生
    MessageCN: 我到了，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030120
    Id: 101030140
    CharacterId: 10103
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 101030110
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 나는 지금 도착했다.
    MessageJP: どこにいる？
    MessageCN: 您在哪里？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030130
    Id: 101030150
    CharacterId: 10103
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 미안, 마리나! 5분 정도 늦을 것 같아!
    MessageJP: ごめん、5分くらい遅れそう！
    MessageCN: 抱歉，可能会迟到5分钟左右！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030140
    Id: 101030160
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그 정도야 아무것도 아니지.
    MessageJP: 大丈夫だ、気を付けて来てくれ
    MessageCN: 没事，慢慢来
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030150
    Id: 101030170
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 광장에서 기다리고 있겠다.
    MessageJP: 広場で待っている
    MessageCN: 我在广场上等着
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030150
    Id: 101030180
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101033
    NextGroupId: 101030160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: ……당혹스러운 경험이었어.
    MessageJP: ……大変だった
    MessageCN: ……好累
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030160
    Id: 101030190
    CharacterId: 10103
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 101030150
    PreConditionFavorScheduleId: 101033
    FavorScheduleId: 0
    NextGroupId: 101030170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그래도 상당히 잘 어울렸어.
    MessageJP: でも、すごくきれいだったよ
    MessageCN: 不过，很漂亮哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030170
    Id: 101030200
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 빈말이라도 그런 말은 하지 말아 주었으면 하는데.
    MessageJP: お、お世辞はやめてくれ
    MessageCN: 奉，奉承话就不用了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030180
    Id: 101030210
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: ……빈말이 아니라면, 더 나쁘고.
    MessageJP: ……お世辞じゃないとしたら、それはもっと困る
    MessageCN: ……是真心话就更加困扰了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030190
    Id: 101030220
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030200
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 벌써부터 여기저기에서, 사진집 잘 봤다는 연락이 들어오고 있으니까…….
    MessageJP: はぁ、いろんな人から写真集の感想が届いてるな
    MessageCN: 哈啊，收到了好多人对写真集的感想
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030200
    Id: 101030230
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030210
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시나 해서 묻는 건데, 선생은 사지 않았겠지?
    MessageJP: 念のために聞くが、先生は買ってないな？
    MessageCN: 姑且问一下，老师您没有买吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030200
    Id: 101030240
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: …….
    MessageJP: ……
    MessageCN: ……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030210
    Id: 101030250
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 잠깐. 그 말줄임표는 뭐지?
    MessageJP: 待て、なぜ何も言わない？
    MessageCN: 等等，为什么沉默了？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030220
    Id: 101030260
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생?
    MessageJP: 先生？
    MessageCN: 老师？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030230
    Id: 101030270
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생?!?!
    MessageJP: 先生！？
    MessageCN: 老师！？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030230
    Id: 101030280
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘 가기로 한 찻집 이름이 뭐였지?
    MessageJP: これから行く喫茶店の名前が思い出せなくてな……
    MessageCN: 我想不起接下来要去的咖啡店的名字……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030240
    Id: 101030290
    CharacterId: 10103
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 101030230
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 도원향이었을걸.
    MessageJP: 「桃源郷」だよ
    MessageCN: 叫「桃源乡」哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030250
    Id: 101030300
    CharacterId: 10103
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030260
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그랬었지.
    MessageJP: ああ、そうだったな
    MessageCN: 啊，是哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030260
    Id: 101030310
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101030270
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 산해경의 차는 어떨까.
    MessageJP: 山海経のお茶はどんな味なのか
    MessageCN: 山海经的茶是什么味道的呢？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030270
    Id: 101030320
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음. 제법 기대가 되는군.
    MessageJP: なかなか楽しみだ
    MessageCN: 好期待啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101030270
    Id: 101030330
    CharacterId: 10103
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101035
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
