CharacterId: 10114
translator: "今天早睡了吗"
title:
  - TextKr: "웨이트리스의 즐거움"
    TextJp: "ウェイトレスの楽しさ"
    TextCn: "侍者的乐趣"
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1011402
    FavorScheduleId: 101142
    CharacterId: 10114
  - TextKr: "웨이트리스의 모험"
    TextJp: "ウェイトレスの冒険"
    TextCn: "侍者的冒险"
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1011403
    FavorScheduleId: 101143
    CharacterId: 10114
  - TextKr: "웨이트리스의 서비스"
    TextJp: "ウェイトレスのサービス"
    TextCn: "侍者的服务"
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1011405
    FavorScheduleId: 101145
    CharacterId: 10114
content:
  - MessageKR: "안녕하세요. 선생님."
    MessageJP: "こんにちは、先生"
    MessageCN: "您好，老师"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140010
    Id: 101140010
    CharacterId: 10114
    MessageCondition: "FavorRankUp"
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140020
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "저, 아르바이트를 시작했어요!"
    MessageJP: "私、アルバイトを始めたんです！"
    MessageCN: "我，开始打工了！"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140020
    Id: 101140020
    CharacterId: 10114
    MessageCondition: "None"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140030
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "아르바이트? 어떤 일인데?"
    MessageJP: "何のバイト？"
    MessageCN: "打的什么工？"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140030
    Id: 101140030
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140040
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "근처 카페에서, 웨이트리스를 해 보기로 했거든요."
    MessageJP: "近くのカフェのホール担当になりました"
    MessageCN: "在最近的咖啡厅做大堂服务生"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140040
    Id: 101140040
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140050
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "저, 선생님?"
    MessageJP: "その……先生"
    MessageCN: "那个……老师"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140050
    Id: 101140050
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140060
    FeedbackTimeMillisec: 1500
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "혹시 괜찮으시면……."
    MessageJP: "もし、よろしければ……"
    MessageCN: "要是，方便的话……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140050
    Id: 101140060
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140060
    FeedbackTimeMillisec: 1500
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "참으로 우연찮게도 지금 이 순간."
    MessageJP: "ちょうど気分転換がしたかったんだ"
    MessageCN: "有点想换换心情啊"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140060
    Id: 101140070
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140070
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
    unsure: false
  - MessageKR: "카페에…… 가고 싶어졌다!"
    MessageJP: "後でお邪魔しようかな"
    MessageCN: "之后我就去叨扰一下吧"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140070
    Id: 101140080
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140080
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "네? 그 말씀은……."
    MessageJP: "……！？"
    MessageCN: "……！？"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140080
    Id: 101140090
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140090
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "감사합니다. 선생님."
    MessageJP: "ありがとうございます、先生！"
    MessageCN: "谢谢您，老师！"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140090
    Id: 101140100
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140100
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "기다릴게요."
    MessageJP: "お待ちしておりますね"
    MessageCN: "恭候您的光临"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140100
    Id: 101140110
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101142
    NextGroupId: 101140110
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "선생님."
    MessageJP: "先生"
    MessageCN: "老师"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140110
    Id: 101140120
    CharacterId: 10114
    MessageCondition: "FavorRankUp"
    ConditionValue: 3
    PreConditionGroupId: 101140100
    PreConditionFavorScheduleId: 101142
    FavorScheduleId: 0
    NextGroupId: 101140120
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
    unsure: false
  - MessageKR: "선생니임……."
    MessageJP: "せんせえ……"
    MessageCN: "老……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140120
    Id: 101140130
    CharacterId: 10114
    MessageCondition: "None"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140130
    FeedbackTimeMillisec: 1500
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "주리? 괜찮아?"
    MessageJP: "ジュリ、大丈夫？"
    MessageCN: "茱莉，你还好吗？"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140130
    Id: 101140140
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140140
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "잠을 제대로 못 잤어요……."
    MessageJP: "昨日もよく眠れませんでした……"
    MessageCN: "昨天基本睡不着……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140140
    Id: 101140150
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140150
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "오늘이 웨이트리스 선발 대회라는 걸 생각했더니"
    MessageJP: "いよいよウェイトレス選抜大会が来たと思うと……"
    MessageCN: "一想到女服务生选拔大赛要到了……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140150
    Id: 101140160
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140160
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "너무 긴장이 되어서……."
    MessageJP: "緊張してしまい……"
    MessageCN: "就好紧张……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140160
    Id: 101140170
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140170
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "제가 잘 해내지 못하면…… 어떡하죠?"
    MessageJP: "もしミスでもしたら……どうしましょう？"
    MessageCN: "要是我比赛里失误了……该怎么办？"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140170
    Id: 101140180
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140180
    FeedbackTimeMillisec: 1500
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "결과에 너무 신경 쓰지 말자……."
    MessageJP: "今は結果を気にしないでおこう"
    MessageCN: "现在就不去想结果的事了吧"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140180
    Id: 101140190
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140190
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "잘 안돼도 좋으니까, 후회만 남기지 말자."
    MessageJP: "もしうまくいかなくても、悔いは残さないようにね"
    MessageCN: "要是不顺利的话，希望茱莉不要一直后悔哦"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140180
    Id: 101140200
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140190
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "네…… 노력해 볼게요."
    MessageJP: "はい……頑張ってみます"
    MessageCN: "嗯……我会努力一下的"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140190
    Id: 101140210
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140200
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "혹시 뭔가 잘 안되면……"
    MessageJP: "その、もしもの時は……"
    MessageCN: "那个，万一出了什么事情……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140200
    Id: 101140220
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140210
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "그때는, 제 손을 잡아 주세요……."
    MessageJP: "私の手を、握ってくれませんか……？"
    MessageCN: "老师能，握住我的手吗……？"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140210
    Id: 101140230
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101143
    NextGroupId: 101140220
    FeedbackTimeMillisec: 1500
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "선생님! 지금 혹시 많이 바쁘신가요?"
    MessageJP: "先生！今お忙しいですか？"
    MessageCN: "老师！您现在忙吗？"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140220
    Id: 101140240
    CharacterId: 10114
    MessageCondition: "FavorRankUp"
    ConditionValue: 5
    PreConditionGroupId: 101140210
    PreConditionFavorScheduleId: 101143
    FavorScheduleId: 0
    NextGroupId: 101140230
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "마침 장난감 택배를 풀어 보고 있었어."
    MessageJP: "通販サイトから買ったおもちゃを開封してるところだよ"
    MessageCN: "正在拆网购来的玩具哦"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140230
    Id: 101140250
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140240
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "그, 그러신가요?"
    MessageJP: "そ、そうでしたか"
    MessageCN: "这、这样啊"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140240
    Id: 101140260
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140250
    FeedbackTimeMillisec: 1500
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "그렇다면 어떤 의미로는 매우 바쁘신 것이……."
    MessageJP: "忙しそうですね……"
    MessageCN: "听起来好像很忙……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140240
    Id: 101140270
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140250
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "완전히 한가하다는 뜻이었습니다."
    MessageJP: "ううん、むしろ暇だよ"
    MessageCN: "没有的事，现在闲得很哦"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140250
    Id: 101140280
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140260
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "그러시군요!"
    MessageJP: "そうでしたか！"
    MessageCN: "这样呀！"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140260
    Id: 101140290
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140270
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "……."
    MessageJP: "その"
    MessageCN: "那个"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140270
    Id: 101140300
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140280
    FeedbackTimeMillisec: 1500
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "저, 선생님."
    MessageJP: "先生"
    MessageCN: "老师"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140270
    Id: 101140310
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140280
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "폐가 되지 않는다면, 이지만……."
    MessageJP: "もし、よろしければ……"
    MessageCN: "要是，方便的话……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140280
    Id: 101140320
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140290
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "저 좀 숨겨 주세요!"
    MessageJP: "私を匿っていただきたいんです！"
    MessageCN: "请把我藏起来……"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140290
    Id: 101140330
    CharacterId: 10114
    MessageCondition: "Feedback"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101140300
    FeedbackTimeMillisec: 1000
    MessageType: "Text"
    ImagePath: ""
  - MessageKR: "……뭐?"
    MessageJP: "……え？"
    MessageCN: "……诶？"
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101140300
    Id: 101140340
    CharacterId: 10114
    MessageCondition: "Answer"
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101145
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: "Text"
    ImagePath: ""
