CharacterId: 10113
translator: ALKA
title:
  - TextJp: 趣味の時間（１）
    TextCn: 兴趣时间（1）
    TextKr: 취미 생활 (1)
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1011302
    FavorScheduleId: 101132
    CharacterId: 10113
  - TextJp: 趣味の時間（２）
    TextCn: 兴趣时间（2）
    TextKr: 취미 생활 (2)
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1011303
    FavorScheduleId: 101133
    CharacterId: 10113
  - TextJp: 表層海流の循環
    TextCn: 表层洋流的循环
    TextKr: 표층 해류의 순환
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 1011305
    FavorScheduleId: 101135
    CharacterId: 10113
content:
  - MessageKR: 선생님, 응급의학부의 히무로 세나입니다.
    MessageJP: 先生、救急医学部の氷室セナです
    MessageCN: 老师，我是急救医学部的冰室濑名
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130010
    Id: 101130010
    CharacterId: 10113
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 비번일이 되었기에, 이에 보고드리려 합니다.
    MessageJP: 本日は非番なので、ご連絡いたしました
    MessageCN: 因为我今天休息，就想着给您发条消息
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130020
    Id: 101130020
    CharacterId: 10113
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 덧붙여, 요즘 선생님을 자주 만나지 못해 쓸쓸하니, 시간 약속을 잡았으면 합니다.
    MessageJP: それと、最近お会いできず寂しいので、少しお時間を頂けたら嬉しいです
    MessageCN: 最近很少见到老师，我感到有些想念。如果能有机会和您聊聊天，我会非常高兴。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130030
    Id: 101130030
    CharacterId: 10113
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 잠깐만. 이야기 좀 따라가자.
    MessageJP: ちょっと待ってね……
    MessageCN: 稍微等我一会儿……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130040
    Id: 101130040
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좋아……. 그래. 이해했어! 그렇게 하자!
    MessageJP: じゃあ、公園で待ち合わせをしようか
    MessageCN: 那就在公园碰头吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130050
    Id: 101130050
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101132
    NextGroupId: 101130060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님, 응급의학부의 히무로 세나입니다.
    MessageJP: 先生、救急医学部の氷室セナです
    MessageCN: 老师，我是急救医学部的冰室濑名
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130060
    Id: 101130060
    CharacterId: 10113
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 101130050
    PreConditionFavorScheduleId: 101132
    FavorScheduleId: 0
    NextGroupId: 101130070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 다시 비번일이 되었기에, 이에 보고드리려 합니다.
    MessageJP: 再び非番となりましたので、報告いたします
    MessageCN: 因为我今天又休息，就想着向您报告一下
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130070
    Id: 101130070
    CharacterId: 10113
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘도 대기할 거야?
    MessageJP: 今日も待機するの？
    MessageCN: 今天也要待命吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130080
    Id: 101130080
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아닙니다. 오늘은 따로 할 일이 있습니다.
    MessageJP: いえ、今日は用事があるので
    MessageCN: 不，今天我有事
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130090
    Id: 101130090
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그래서 사복을 입고 응급의학부실을 찾으려 합니다.
    MessageJP: 私服で救急医学部の部室に行こうと思います
    MessageCN: 我打算先穿便服去趟急救医学部的活动室
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130100
    Id: 101130100
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 비번일에…… 사복으로…… 동아리실에?
    MessageJP: 非番の日に、私服で部室に……？
    MessageCN: 休息日，穿便服去部室……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130110
    Id: 101130110
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 나도 갈게!
    MessageJP: 私も行くよ！
    MessageCN: 我也去！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130120
    Id: 101130120
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네?
    MessageJP: はい……？
    MessageCN: 嗯……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130130
    Id: 101130130
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 별다를 것은 없을 것이라고 생각합니다만.
    MessageJP: いつも忙しいはずでは……
    MessageCN: 明明平常很忙的才对……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130130
    Id: 101130140
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아무튼 갈게!
    MessageJP: とにかく行くよ！
    MessageCN: 总之我要去！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130140
    Id: 101130150
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130150
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음.
    MessageJP: ……
    MessageCN: ……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130150
    Id: 101130160
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130160
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 알겠습니다.
    MessageJP: 分かりました
    MessageCN: 我知道了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130150
    Id: 101130170
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130160
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼 그렇게 알고 있겠습니다.
    MessageJP: では、お待ちしております
    MessageCN: 那我等您
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130160
    Id: 101130180
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101133
    NextGroupId: 101130170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님, 응급의학부의 히무로 세나입니다.
    MessageJP: 先生、救急医学部の氷室セナです
    MessageCN: 老师，我是急救医学部的冰室濑名
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130170
    Id: 101130190
    CharacterId: 10113
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 101130160
    PreConditionFavorScheduleId: 101133
    FavorScheduleId: 0
    NextGroupId: 101130180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 최근 비슷한 말씀을 자주 드리게 되는 것 같습니다만.
    MessageJP: 最近、同じ報告を何度もしている気がしますが……
    MessageCN: 感觉最近一直在做同样的报告……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130180
    Id: 101130200
    CharacterId: 10113
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130190
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 세나의 비번!
    MessageJP: セナの非番！
    MessageCN: 濑名的休息日！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130190
    Id: 101130210
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음.
    MessageJP: ……
    MessageCN: ……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130200
    Id: 101130220
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130210
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 역시 선생님께는 아무것도 숨길 필요가 없군요.
    MessageJP: その通りです
    MessageCN: 是的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130200
    Id: 101130230
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘은 대기? 약품 정비?
    MessageJP: 今日は何するの？待機？薬の整備？
    MessageCN: 今天要做什么？待命？整理药品？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130210
    Id: 101130240
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네. 바로 그 부분입니다.
    MessageJP: 今日は普段と違う予定があります
    MessageCN: 今天的安排和平常不太一样
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130220
    Id: 101130250
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이례적인 일이 발생하였다고 말씀드리려 했던 것은.
    MessageJP: 極めて例外的な状況だと
    MessageCN: 是极其特殊的状况
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130220
    Id: 101130260
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 드물게도 저에게, 상정 외의 생각이 떠올랐기 때문이었습니다.
    MessageJP: ご理解いただけると助かります
    MessageCN: 希望您能理解
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130230
    Id: 101130270
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130240
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그게…… 뭔데?
    MessageJP: それって……何？
    MessageCN: 那……是什么呢？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130240
    Id: 101130280
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 바다에 가 보고 싶습니다.
    MessageJP: 海を見に行きたいです
    MessageCN: 我想去看海
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130250
    Id: 101130290
    CharacterId: 10113
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130260
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: "!!!"
    MessageJP: ！！！
    MessageCN: ！！！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130260
    Id: 101130300
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 101130270
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 알았어! 내게 맡겨!!!
    MessageJP: 分かった、私に任せて！
    MessageCN: 我明白了，包在我身上！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 101130270
    Id: 101130310
    CharacterId: 10113
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 101135
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
