CharacterId: 16012
translator: 今天早睡了吗
title:
  - TextJp: 新年を新たな装いで！
    TextCn: 新年穿新衣！
    TextKr: 새해에는 새 옷으로!
    TextEn: New Year, New Clothes! New Me?
    TextTh: ปีใหม่ก็ต้องใส่ชุดใหม่!
    TextTw: 新年穿新衣！
    GroupId: 1601202
    FavorScheduleId: 160122
    CharacterId: 16012
  - TextJp: 色んな料理が食べたい！
    TextCn: 想吃各种料理！
    TextKr: 다양한 음식이 필요해!
    TextEn: More Food, More Fun! More Me?
    TextTh: ต้องการอาหารที่หลากหลาย!
    TextTw: 想吃各種料理！
    GroupId: 1601203
    FavorScheduleId: 160123
    CharacterId: 16012
  - TextJp: ぬくもりをください
    TextCn: 请给我温暖
    TextKr: 따스함을 주세요
    TextEn: Gimme Warmth
    TextTh: ขอความนุ่มนิ่ม
    TextTw: 請給我溫暖
    GroupId: 1601205
    FavorScheduleId: 160125
    CharacterId: 16012
content:
  - MessageKR: 선생님, 오늘 바빠?
    MessageJP: 先生、今日って忙しい？
    MessageCN: 老师今天忙吗？
    MessageEN: Hey Sensei! Are you busy today?
    MessageTH: คุณครู วันนี้ยุ่งรึเปล่า?
    MessageTW: 老師，你今天忙嗎？
    MessageGroupId: 160120010
    Id: 160120010
    CharacterId: 16012
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 너무 바쁘지 않다면 내가 아르바이트 하는 곳에 와 볼래?
    MessageJP: もし時間があったら、私のバイト先に来てくれない？
    MessageCN: 如果老师有时间的话，能麻烦老师来一趟我打工的地方吗？
    MessageEN: If not, come stop by my work!
    MessageTH: "ถ้างานไม่ยุ่งมาก ช่วยออกมาที่ที่ฉัน

      ทำงานพิเศษอยู่หน่อยได้มั้ย?"
    MessageTW: 有時間的話，要不要來我打工的地方一趟？
    MessageGroupId: 160120020
    Id: 160120020
    CharacterId: 16012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120030
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어디였더라…… <르와조 블뢰>였던가?
    MessageJP: 確か……「ルワゾー・ブッレ」、だったっけ？
    MessageCN: 我记得那个地方是叫……“Loulseau Bulle”来着，应该没记错吧？
    MessageEN: Oh, where was that again? L'Oiseau Bleu?
    MessageTH: "ที่ไหนนะ...

      ร้าน <ลูวาโซ บลู> ใช่มั้ย?"
    MessageTW: 我記得……是「L'Oiseau Bleu」嗎？
    MessageGroupId: 160120030
    Id: 160120030
    CharacterId: 16012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 맞아. 잘 기억하고 있네.
    MessageJP: そうそう。っていうか、よく覚えてたわね
    MessageCN: 对对对。说起来，老师记得还真清楚啊
    MessageEN: Yep, that's right!
    MessageTH: ใช่แล้ว จำแม่นดีจัง
    MessageTW: 沒錯沒錯。話說，虧你還記得呢
    MessageGroupId: 160120040
    Id: 160120040
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 조금, 보여 주고 싶은 게 생겼거든.
    MessageJP: ちょっと先生に見せたいものがあるの
    MessageCN: 我有个东西想给老师看看
    MessageEN: I wanna show you something.
    MessageTH: ฉันมีบางอย่างอยากให้คุณครูดูน่ะ
    MessageTW: 有個東西想讓老師看看
    MessageGroupId: 160120040
    Id: 160120050
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 기다리고 있을 테니까!
    MessageJP: 待ってるから、ちゃんと来てね！
    MessageCN: 老师一定要来哦，我就在这等您！
    MessageEN: I'll be waiting!
    MessageTH: ฉันจะรออยู่ที่ร้านนะ!
    MessageTW: 我等你，一定要來哦！
    MessageGroupId: 160120050
    Id: 160120060
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 160122
    NextGroupId: 160120060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님, 선생님!
    MessageJP: 先生、先生！
    MessageCN: 老师，老师！
    MessageEN: Sensei, Sensei!
    MessageTH: คุณครู คุณครู!
    MessageTW: 老師，老師！
    MessageGroupId: 160120060
    Id: 160120070
    CharacterId: 16012
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 160120050
    PreConditionFavorScheduleId: 160122
    FavorScheduleId: 0
    NextGroupId: 160120070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아르바이트비를 받았어!
    MessageJP: バイト代が入ったの！
    MessageCN: 我拿到打工的工资啦！
    MessageEN: I got my paycheck!
    MessageTH: ได้เงินค่าทำงานพาร์ทไทม์แล้วละ!
    MessageTW: 我收到打工的薪水了！
    MessageGroupId: 160120060
    Id: 160120080
    CharacterId: 16012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 축하해. 준코가 노력한 대가야.
    MessageJP: ジュンコが頑張ったからだね
    MessageCN: 毕竟纯子很努力呢
    MessageEN: Congrats! You deserve it.
    MessageTH: "ดีใจด้วยนะ ถือเป็นค่าตอบแทน

      ความพยายามของจุนโกะไง"
    MessageTW: 因為淳子很努力呀
    MessageGroupId: 160120070
    Id: 160120090
    CharacterId: 16012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그래서 말인데
    MessageJP: まぁね！というわけで……
    MessageCN: 就是啊！所以……
    MessageEN: So, now...
    MessageTH: เพราะงั้น...
    MessageTW: 也對！所以說……
    MessageGroupId: 160120080
    Id: 160120100
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 되갚아 줄 거야!
    MessageJP: お返しの時間よ！
    MessageCN: 现在是偿还时间哦！
    MessageEN: It's time to get even!
    MessageTH: คราวนี้ถึงตาฉันตอบแทนคุณครูบ้างแล้วละ!
    MessageTW: 現在是回禮時間唷！
    MessageGroupId: 160120080
    Id: 160120110
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120090
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: ……그건 또 무슨 소리야?
    MessageJP: ……どういうこと？
    MessageCN: ……什么意思？
    MessageEN: "...What do you mean by that, exactly?"
    MessageTH: หมายความว่าไงน่ะ?
    MessageTW: ……什麼意思？
    MessageGroupId: 160120090
    Id: 160120120
    CharacterId: 16012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 목숨만은 살려주세요!
    MessageJP: ど、どうか命だけは……
    MessageCN: 请、请务必给我留一条命……
    MessageEN: Please don't hurt me...
    MessageTH: ไว้ชีวิตครูด้วยเถอะ!
    MessageTW: 請，請留小的一命……
    MessageGroupId: 160120090
    Id: 160120130
    CharacterId: 16012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 후훗. 두고 보라고.
    MessageJP: ふふっ、見てなさい
    MessageCN: 哼哼，老师就等着吧
    MessageEN: Heehee, you'll see!
    MessageTH: ฮุฮุ คอยดูเถอะ
    MessageTW: 呵呵，等著看吧
    MessageGroupId: 160120100
    Id: 160120140
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이상한 짓 하려는 거 아니거든?!
    MessageJP: 物騒なこと言わないで！
    MessageCN: 不要说这种危险的话啊！
    MessageEN: But it's not gonna be weird or anything.
    MessageTH: ฉันไม่ได้จะทำอะไรแปลกๆ สักหน่อย?!
    MessageTW: 別說那種奇怪的話！
    MessageGroupId: 160120110
    Id: 160120150
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: "내가 뭘 하려는지 궁금하다면 "
    MessageJP: とにかく
    MessageCN: 总之
    MessageEN: You're curious though, right?
    MessageTH: ถ้าอยากรู้ว่าฉันจะทำอะไร
    MessageTW: 總之
    MessageGroupId: 160120120
    Id: 160120160
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 오늘 저녁 시간에 맞춰 축제 거리로 찾아와.
    MessageJP: 夕方になったら、お祭り通りに来て
    MessageCN: 老师就在傍晚的时候到祭典大道这边来吧
    MessageEN: So come to the festival street this evening.
    MessageTH: เย็นนี้ก็ออกมาที่งานเทศกาลสิ
    MessageTW: 傍晚來慶典大街一趟吧
    MessageGroupId: 160120130
    Id: 160120170
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120140
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 꼭이야!
    MessageJP: 絶対よ！
    MessageCN: 一定要来哦！
    MessageEN: Promise me!
    MessageTH: ต้องมานะ!
    MessageTW: 一定要唷！
    MessageGroupId: 160120140
    Id: 160120180
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 160123
    NextGroupId: 160120150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 연휴가
    MessageJP: 連休が
    MessageCN: 连休
    MessageEN: The holiday...
    MessageTH: วันหยุดยาว...
    MessageTW: 連假
    MessageGroupId: 160120150
    Id: 160120190
    CharacterId: 16012
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 160120140
    PreConditionFavorScheduleId: 160123
    FavorScheduleId: 0
    NextGroupId: 160120160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 끝났어
    MessageJP: 終わった
    MessageCN: 结束了
    MessageEN: The holiday is over.
    MessageTH: จบแล้ว
    MessageTW: 結束了
    MessageGroupId: 160120160
    Id: 160120200
    CharacterId: 16012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 끝나버렸어
    MessageJP: 終わっちゃった……
    MessageCN: 已经结束了……
    MessageEN: It's all over.
    MessageTH: มันจบสิ้นแล้ว...
    MessageTW: 都結束了……
    MessageGroupId: 160120170
    Id: 160120210
    CharacterId: 16012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 진정해 준코. 연휴는 일단 내일까지야.
    MessageJP: お、落ち着いて、ジュンコ。連休は一応明日までだよ
    MessageCN: 冷、冷静一下纯子。至少连休还有明天最后一天呢
    MessageEN: Junko, calm down. You've got one more day.
    MessageTH: "ใจเย็นๆ นะจุนโกะ วันหยุดยาวน่ะ

      มันถึงวันพรุ่งนี้ต่างหากล่ะ"
    MessageTW: 冷，冷靜點，淳子。連假明天才結束唷
    MessageGroupId: 160120180
    Id: 160120220
    CharacterId: 16012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그 정도는 알아!
    MessageJP: 知ってるわよ！
    MessageCN: 我当然知道！
    MessageEN: I know!
    MessageTH: เรื่องนั้นฉันรู้น่า!
    MessageTW: 我知道啦！
    MessageGroupId: 160120190
    Id: 160120230
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 하지만 내 마음속에서 연휴는 이미 죽었어! 더는 없어!
    MessageJP: でも私の心の中での連休は死んだ！もういない！
    MessageCN: 但是连休在我心里已经死了！已经不在了！
    MessageEN: But in my soul, it's gone... vanished...
    MessageTH: "แต่ว่าในใจฉันน่ะ วันหยุดมันหมด

      ไปแล้ว! ไม่มีอีกแล้ว!"
    MessageTW: 但是我心中的連假已經死了！已經不在了！
    MessageGroupId: 160120200
    Id: 160120240
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120210
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 내 등에, 이 가슴에, 하나가 되어 함께 살아가지도 않아!
    MessageJP: 私の背中にもこの胸にも、一つになって生き続けてくれない！
    MessageCN: 它已经不能像之前那样继续活在我的心里、住在我的身体里了！
    MessageEN: What's the point when I don't feel the holiday spirit anymore?
    MessageTH: "มันจะมีประโยชน์อะไร ในเมื่อฉันไม่รู้สึก

      ถึงความพิเศษของวันหยุดอีกแล้ว?"
    MessageTW: 沒有在我的背上或胸膛和我一起活下去！
    MessageGroupId: 160120200
    Id: 160120250
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 160120210
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 남은 연휴를 이대로 보낼 순 없다고!
    MessageJP: でもだからって、このまま終わらせるわけにはいかないの！
    MessageCN: 但正因为这样，我不能让假期就这么结束！
    MessageEN: My precious holiday can't disappear like this!
    MessageTH: "จะปล่อยให้วันหยุดแสนสำคัญของฉัน

      ผ่านไปแบบนี้ได้ยังไง!"
    MessageTW: 不過儘管如此，也不能就這麼結束！
    MessageGroupId: 160120210
    Id: 160120260
    CharacterId: 16012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 160125
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
