CharacterId: 20038
translator: 今天早睡了吗
title:
  - TextJp: 話を聞く技術
    TextCn: 倾听的技巧
    TextKr: 들어주는 하루
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003802
    FavorScheduleId: 200382
    CharacterId: 20038
  - TextJp: 寒国の秘書室長
    TextCn: 寒国的秘书室长
    TextKr: 추운 나라에서 온 비서실장
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003803
    FavorScheduleId: 200383
    CharacterId: 20038
  - TextJp: 毎日健康生活
    TextCn: 每日健康生活
    TextKr: 간판 소녀
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003805
    FavorScheduleId: 200385
    CharacterId: 20038
content:
  - MessageKR: 산해경에서의 생활은, 확실히 신선하네요.
    MessageJP: 山海経での生活は、たしかに新鮮ですね
    MessageCN: 在山海经的生活，确实很新鲜呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380010
    Id: 200380010
    CharacterId: 20038
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 조금 익숙해졌어?
    MessageJP: ちょっとは慣れてきた？
    MessageCN: 已经习惯一些了吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380020
    Id: 200380020
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 익숙해졌다면 익숙해졌다고 말씀드려야겠지만…….
    MessageJP: まだ少しですが……
    MessageCN: 虽然还有个别地方不太适应……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380030
    Id: 200380030
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좀처럼 익숙해지고 싶지 않다는 생각도 들기는 하네요.
    MessageJP: あまり慣れてしまいたくない気持ちもあります
    MessageCN: 但是我也不想太过习惯
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380030
    Id: 200380040
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그건 어째서?
    MessageJP: どうして？
    MessageCN: 为什么？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380040
    Id: 200380050
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 음……. 글쎄요?
    MessageJP: うーん……
    MessageCN: 唔……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380050
    Id: 200380060
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 너무 익숙해져 버리면
    MessageJP: やはり、慣れてしまったら
    MessageCN: 要是完全习惯了的话
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380060
    Id: 200380070
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 역시 신선함과 즐거움이 줄어들지도 모르니까요?
    MessageJP: この楽しい気持ちが減ってしまうから、でしょうか
    MessageCN: 这种快乐的心情就一定会减少了吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380060
    Id: 200380080
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200382
    NextGroupId: 200380070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 확실히 다른 학원에 오게 되어서 느끼는 것입니다만.
    MessageJP: あらためて感じたのですが
    MessageCN: 我又一次感觉到了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380070
    Id: 200380090
    CharacterId: 20038
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200380060
    PreConditionFavorScheduleId: 200382
    FavorScheduleId: 0
    NextGroupId: 200380080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 산해경과 붉은겨울 사이에는 참 많은 차이가 있군요.
    MessageJP: 山海経とレッドウィンターは、本当に色々なところが違いますね
    MessageCN: 山海经和红冬，真的有很多地方都不一样呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380080
    Id: 200380100
    CharacterId: 20038
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어떤 부분이 특히 그래?
    MessageJP: 具体的にはどこが違った？
    MessageCN: 具体来说有哪些不一样？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380090
    Id: 200380110
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 더워요.
    MessageJP: 一番は暑さです
    MessageCN: 最大的不同就是山海经很热
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380100
    Id: 200380120
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380110
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 가만히 있어도 땀이 나는 경험이란……
    MessageJP: ジッとしていても汗をかくだなんて
    MessageCN: 哪怕一动不动居然都会出汗
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380110
    Id: 200380130
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 솔직히, 처음 겪는 것이네요.
    MessageJP: 初めての経験で
    MessageCN: 我还是第一次体验到这种温度
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380110
    Id: 200380140
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아, 확실히 붉은겨울에 비하면…….
    MessageJP: たしかに、そうだよね
    MessageCN: 确实是这样呢
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380120
    Id: 200380150
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: "물론 붉은겨울에 비해서 "
    MessageJP: もちろん
    MessageCN: 当然
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380130
    Id: 200380160
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 더 '시원한' 곳이 얼마나 있을까, 하는 생각이 들기도 하지만.
    MessageJP: レッドウィンターより涼しいところのほうが少ないと思いますが
    MessageCN: 虽然我觉得比红冬更凉快的地方应该很少
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380130
    Id: 200380170
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그렇다고는 해도, 이건 확실히 쉽지 않군요.
    MessageJP: これは予想以上でした
    MessageCN: 但是这里也超出我的预期了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380140
    Id: 200380180
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200383
    NextGroupId: 200380150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선~ 생~ 님~
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380150
    Id: 200380190
    CharacterId: 20038
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200380140
    PreConditionFavorScheduleId: 200383
    FavorScheduleId: 0
    NextGroupId: 200380160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 바쁘신가요?
    MessageJP: 今、お忙しいでしょうか？
    MessageCN: 您现在在忙吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380160
    Id: 200380200
    CharacterId: 20038
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380170
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 마침 한가한데, 무슨 일이야?
    MessageJP: 手なら空いてるよ、どうしたの？
    MessageCN: 我有空哦，怎么了？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380170
    Id: 200380210
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380180
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 괜찮으시다면, 점심이라도 함께 하시면 어떨까 해서요.
    MessageJP: よろしければ、お昼をご一緒したいと思いまして
    MessageCN: 要是老师方便，我想和老师共进午餐
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380180
    Id: 200380220
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론 선생님께서 괜찮으실 때의 이야기이겠지만요.
    MessageJP: もちろん、先生がよろしければですが
    MessageCN: 当然，如果老师不介意的话
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380180
    Id: 200380230
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380190
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 좋았어! 맛있는 중화 요리 가게를 소개해 줄게!
    MessageJP: じゃあ、有名な中華料理屋さんを紹介するね！
    MessageCN: 那么，我给巴推荐一家很有名的中餐店吧！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380190
    Id: 200380240
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380200
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그런데 생각해 보니까…… 중화 요리는 제법 많이 맛보지 않았어?
    MessageJP: と思ったけど、トモエならもう知ってるような気も
    MessageCN: ……虽然我是这么想的，不过既然是巴发出的邀请，你应该已经知道是哪家了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380200
    Id: 200380250
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그렇기는 하지만
    MessageJP: たしかに、色々と事前に調べてから来ましたが……
    MessageCN: 确实，我事先做了许多调查才来邀请您……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380210
    Id: 200380260
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님께서 직접 소개해 주시고, 데려가 주신다니.
    MessageJP: 先生に紹介していただけるのでしたら
    MessageCN: 不过如果是由老师介绍给我的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380210
    Id: 200380270
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그것은 또 나름 각별한 가게가 될 것 같아서 기대가 되네요.
    MessageJP: 嬉しい限りです
    MessageCN: 我就再高兴不过了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380220
    Id: 200380280
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 기대가 너무 크면, 실망할지도 모르는데…….
    MessageJP: 期待に応えられるか心配だけど……
    MessageCN: 虽然我有点担心能不能满足你的期待……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380230
    Id: 200380290
    CharacterId: 20038
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380240
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: "그럴 일은 없을 거라고 "
    MessageJP: 断言できます
    MessageCN: 我可以断言
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380240
    Id: 200380300
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380250
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 단언드릴 수 있을 것 같네요.
    MessageJP: 心配はいりません
    MessageCN: 您无需担心
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380240
    Id: 200380310
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200380250
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 왜냐하면, 선생님과 같이 가는 가게인걸요?
    MessageJP: 先生が一緒に来てくださるんですから
    MessageCN: 毕竟是老师和我一起来的地方
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200380250
    Id: 200380320
    CharacterId: 20038
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200385
    NextGroupId: 0
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
