CharacterId: 20037
translator: DragonCan@资讯站
title:
  - TextKr: 폴리스 스토리-식당가 편
    TextJp: ポリス・ストーリー～フードコート編～
    TextCn: 警察故事〜美食广场篇〜
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003702
    FavorScheduleId: 200372
    CharacterId: 20037
    unsure: false
  - TextKr: 폴리스 스토리-유수풀 편
    TextJp: ポリス・ストーリー～流れるプール編～
    TextCn: 警察故事〜漂流泳池篇〜
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003703
    FavorScheduleId: 200373
    CharacterId: 20037
    unsure: false
  - TextKr: 폴리스 스토리-로스트 파라다이스 편
    TextJp: ポリス・ストーリー～ロスト・パラダイス編～
    TextCn: 警察故事～失落天堂篇～
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2003705
    FavorScheduleId: 200375
    CharacterId: 20037
    unsure: false
content:
  - MessageKR: 감찰관! 감찰관!
    MessageJP: 監察官！
    MessageCN: 监察官！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370010
    Id: 200370010
    CharacterId: 20037
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 지금 어디 있어? 바쁜 일이라도 있어?
    MessageJP: 今どこ？忙しい？
    MessageCN: 您现在在哪？忙吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370020
    Id: 200370020
    CharacterId: 20037
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 감찰관……?
    MessageJP: 監察官……？
    MessageCN: 监察官……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370030
    Id: 200370030
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 아니, 한가하게 돌아다니고 있는데.
    MessageJP: のんびりしてるよ
    MessageCN: 我在休息哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370030
    Id: 200370040
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370050
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 자, 자, 사소한 건 됐고!
    MessageJP: 細かいことは良いの！
    MessageCN: 没时间细说了！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370040
    Id: 200370050
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 지금 바로 파크 내의 푸드코트로 와 줘.
    MessageJP: 至急、パーク内のフードコートに来て
    MessageCN: 快来公园的美食广场
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370050
    Id: 200370060
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 사람들의 안전과 관련된 급한 공무니까! 얼른 와 줘야 돼!
    MessageJP: 市民の安全に関わることだから！急いでね！
    MessageCN: 这关乎市民的安全！请快一点！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370050
    Id: 200370070
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370060
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: ……?
    MessageJP: ……？
    MessageCN: ……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370060
    Id: 200370080
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200372
    NextGroupId: 200370070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 오늘 임무는 마음에 들어.
    MessageJP: 今日の任務は、パークのパトロールだって
    MessageCN: 我今天的任务，是巡视水上乐园
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370070
    Id: 200370090
    CharacterId: 20037
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 200370060
    PreConditionFavorScheduleId: 200372
    FavorScheduleId: 0
    NextGroupId: 200370080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 파크 전체를 순찰하는 임무거든.
    MessageJP: 結構楽しそうじゃない？
    MessageCN: 不觉得挺有意思吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370080
    Id: 200370100
    CharacterId: 20037
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 후부키는 움직이는 거 싫어하지 않았어?
    MessageJP: フブキって仕事が嫌いだったよね……？
    MessageCN: 吹雪你不是挺讨厌工作的吗……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370090
    Id: 200370110
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 그럴 리가 있나? 순찰이야말로 라이프가드 임무의 꽃인걸.
    MessageJP: 何を言ってるのさ、先生
    MessageCN: 您在说什么啊，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370100
    Id: 200370120
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370110
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 사람들의 안전을 책임지는 라이프가드로서 당연히 해야 할 일이지.
    MessageJP: 人々の安全を守るためなんだから、喜んでやるに決まってるでしょ
    MessageCN: 这可是为了保护人们的安全，我当然是乐意的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370100
    Id: 200370130
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370110
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 뭔가 수상한데.
    MessageJP: 何か怪しいような……
    MessageCN: 感觉好可疑……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370110
    Id: 200370140
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370120
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 어허, 그게 무슨 말이야.
    MessageJP: 大丈夫大丈夫、真面目にやるってば
    MessageCN: 没事啦没事啦，我会认真对待的啦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370120
    Id: 200370150
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 파크를 뱅글뱅글 돌면서 성실하게 순찰할 거라고.
    MessageJP: パークをぐるぐる回りながらね
    MessageCN: 一边骨碌骨碌转着一边巡视
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370120
    Id: 200370160
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370130
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 뱅글뱅글……?
    MessageJP: ぐるぐる……？
    MessageCN: 骨碌骨碌……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370130
    Id: 200370170
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200373
    NextGroupId: 200370140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 너무해, 선생…….
    MessageJP: ひどいよ、先生……
    MessageCN: 太过分了，老师……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370140
    Id: 200370180
    CharacterId: 20037
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 200370130
    PreConditionFavorScheduleId: 200373
    FavorScheduleId: 0
    NextGroupId: 200370150
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 정말로 걸어서 순찰하게 하다니.
    MessageJP: 本当に歩いてパトロールさせるだなんて
    MessageCN: 竟然真的让我走着巡视
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370140
    Id: 200370190
    CharacterId: 20037
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 원래 그런 임무잖아?
    MessageJP: 大げさだなあ
    MessageCN: 没这么夸张吧
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370150
    Id: 200370200
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 누가 보면 하면 안 되는 일이라도 시킨 줄 알겠다!
    MessageJP: 元々そういう仕事でしょ？
    MessageCN: 本来就是这样的工作吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370150
    Id: 200370210
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 연약한 학생에게 햇빛은 독이라구, 독.
    MessageJP: 夏の日差しは大敵なのに！
    MessageCN: 明明夏天的阳光是大敌！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370160
    Id: 200370220
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: true
  - MessageKR: 뭐, 그 뒤에 사 준 아이스크림은 맛있었지만 말이야.
    MessageJP: ま、先生が奢ってくれたアイス、美味しかったし
    MessageCN: 不过老师您请我吃的冰淇淋，还挺好吃的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370160
    Id: 200370230
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370170
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: …….
    MessageJP: 先生と一緒だったら
    MessageCN: 和老师在一起的话
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370170
    Id: 200370240
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 응, 선생과 함께라면 가끔씩은 성실하게 순찰하는 것도 나쁘지 않을지도 모르겠네.
    MessageJP: たまには真面目にパトロールするのも悪くないかもね
    MessageCN: 偶尔认真巡逻一下也挺不错
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370170
    Id: 200370250
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 드디어 내 파라다이스를 찾았어.
    MessageJP: 私だけのパラダイスを見つけたよ
    MessageCN: 我找到了只属于我的天堂。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370180
    Id: 200370260
    CharacterId: 20037
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 200370170
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 누구에게도 방해받지 않는 안식의 땅…….
    MessageJP: 誰にも邪魔されない、安息の地……
    MessageCN: 不被任何人打扰的，安息之地……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370190
    Id: 200370270
    CharacterId: 20037
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 이곳이라면 누구의 눈치도 받지 않고 쉴 수 있어……!
    MessageJP: これで、ようやく気ままに過ごせるね
    MessageCN: 这么一来，终于可以随心所欲了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370190
    Id: 200370280
    CharacterId: 20037
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 숨어 있을 곳이라도 찾은 거야?
    MessageJP: 隠れ家でも作ったの？
    MessageCN: 你还建了个秘密基地？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370200
    Id: 200370290
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 농땡이 피울 곳을 찾은 모양이네.
    MessageJP: サボり場所を見つけたんだね
    MessageCN: 是发现偷懒的地方了吧。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370200
    Id: 200370300
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 선생님도 구경 올래?
    MessageJP: 先生も見にくる？
    MessageCN: 老师也来看看吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370210
    Id: 200370310
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 대신 물에 들어가면 안 돼.
    MessageJP: あっ、でもプールには入らないでね
    MessageCN: 啊，不过别进游泳池哦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370210
    Id: 200370320
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370220
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 내가 감시해야 할 이용객이 느는 건 사양이니까.
    MessageJP: 監視対象が増えるとめんどくさいからさ
    MessageCN: 要注意的对象增加了可就麻烦了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370220
    Id: 200370330
    CharacterId: 20037
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 200370230
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
    unsure: false
  - MessageKR: 워터파크에서 물에 들어가지 말라니…….
    MessageJP: ウォーターパークなのに……？
    MessageCN: 明明是水上乐园却不能下水……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 200370230
    Id: 200370340
    CharacterId: 20037
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 200375
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
    unsure: false
