CharacterId: 26001
translator: 今天早睡了吗
title:
  - GroupId: 2600102
    FavorScheduleId: 260012
    CharacterId: 26001
    TextJp: 大人の秘密
    TextCn: 大人的秘密
    TextKr: 어른의 비밀
    TextEn: Grown-Up Secrets
    TextTh: ความลับของผู้ใหญ่
    TextTw: 大人的秘密
  - GroupId: 2600103
    FavorScheduleId: 260013
    CharacterId: 26001
    TextJp: メリーさんの電波
    TextCn: 玛丽的电波
    TextKr: 메리 씨의 전파
    TextEn: The Voice of Mary
    TextTh: เสียงของคุณแมรี่
    TextTw: 瑪莉小姐的電波
  - GroupId: 2600105
    FavorScheduleId: 260015
    CharacterId: 26001
    TextJp: 言えないこと
    TextCn: 不能说的事情
    TextKr: 말할 수 없는 비밀
    TextEn: Unspeakable Secrets
    TextTh: ความลับที่บอกใครไม่ได้
    TextTw: 難以說出口的事
  - GroupId: 2600106
    FavorScheduleId: 260016
    CharacterId: 26001
    TextJp: まっしろで透き通るような
    TextCn: 纯白且透明的
    TextKr: 한없이 투명에 가까운 백색
    TextEn: ''
    TextTh: ''
    TextTw: ''
content:
  - MessageGroupId: 260010010
    Id: 1558
    CharacterId: 26001
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 선생님.
    MessageJP: 先生、先生
    MessageCN: 老师，老师
    MessageEN: Sensei! Sensei!
    MessageTH: คุณครูคะ คุณครู!
    MessageTW: 老師，老師
  - MessageGroupId: 260010020
    Id: 1559
    CharacterId: 26001
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님은 특별히 좋아하는 물건이 있으십니까?
    MessageJP: 先生は、何かいつも大事にしているものはありますか？
    MessageCN: 老师有什么一直以来都非常珍视的东西吗？
    MessageEN: Is there something that you particularly like?
    MessageTH: คุณครูมีของที่ชอบเป็นพิเศษรึเปล่าคะ?
    MessageTW: 老師有什麼一直都很重視的東西嗎？
  - MessageGroupId: 260010030
    Id: 1560
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 갑자기 그렇게 물어봐도 잘 모르겠는데…….
    MessageJP: パッと思いつくものは無いかな……
    MessageCN: 小玉突然问这个的话，一时间还真想不到……
    MessageEN: That's a very broad question...
    MessageTH: จู่ๆ มาถามแบบนี้ก็คิดไม่ออกหรอก...
    MessageTW: 一時之間想不太到……
  - MessageGroupId: 260010040
    Id: 1561
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010050
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 특별히 좋아해서 수집하는 물건은 없으신가요?
    MessageJP: 特別に好きで、集めているものは？
    MessageCN: 那老师有没有特别喜欢的，一直在收集的东西呢？
    MessageEN: Like something you collect?
    MessageTH: 'ไม่มีของที่ชอบมากๆ จนชอบเก็บสะสม

      เลยเหรอคะ?'
    MessageTW: 有沒有特別喜歡、收藏的東西呢？
  - MessageGroupId: 260010040
    Id: 1562
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010050
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 특별히 좋아해서 하루 종일 들고 다니는 물건은 없으신가요?
    MessageJP: お気に入りで、一日中持ち歩いてるものは？
    MessageCN: 很喜欢的、天天带在身上的东西呢？
    MessageEN: Or something you carry around all day long?
    MessageTH: 'ของที่ชอบมากๆ จนอยากจะถือไปมา

      ตลอดทั้งวันก็ไม่มีเหรอคะ?'
    MessageTW: 或者是很中意、總是帶在身邊的東西呢？
  - MessageGroupId: 260010040
    Id: 1563
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010050
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ''
    MessageKR: 특별히 좋아해서 몸에서 조금이라도 떨어지면 불안을 느끼는 물건은 없으신가요?
    MessageJP: 肌身離さず持っていて、少し手放すと不安になるもの、何かありませんか？
    MessageCN: 随身携带的，哪怕稍微离开身边一小会就会感到不安的东西呢？有吗？
    MessageEN: Like if you leave it behind, you feel anxious all day?
    MessageTH: 'ของที่ชอบมากๆ จนถ้าไปวางไว้ห่างตัว

      ก็จะรู้สึกไม่สบายใจน่ะค่ะ?'
    MessageTW: 還是說有從不離身，只要一放手就渾身不安的東西呢？
  - MessageGroupId: 260010050
    Id: 1564
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……그런 특별한 취향은 내게 없어.
    MessageJP: そこまで執着するようなものは、私にはないかなあ……
    MessageCN: 我大概没有对什么东西执着到那种程度吧……
    MessageEN: Not really...
    MessageTH: 'ครู... ไม่มีอะไรที่ชอบเป็นพิเศษ

      แบบนั้นหรอก'
    MessageTW: 我好像沒有執著到這種程度的東西……
  - MessageGroupId: 260010060
    Id: 1565
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그런가요……. 조금 어렵게 되었군요.
    MessageJP: そうですか……難しいですね
    MessageCN: 这样啊……那就难办了呢
    MessageEN: Really? Then that might make things difficult...
    MessageTH: อย่างงั้นเหรอคะ... ยุ่งยากแล้วล่ะสิ
    MessageTW: 是嗎……這下麻煩了
  - MessageGroupId: 260010070
    Id: 1566
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010080
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 뭐가 어렵다는 말이야?
    MessageJP: 何が難しいの？
    MessageCN: 是什么东西难办呢？
    MessageEN: What will be difficult?
    MessageTH: อะไรยุ่งยากเหรอ?
    MessageTW: 什麼麻煩？
  - MessageGroupId: 260010080
    Id: 1567
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260012
    NextGroupId: 260010090
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아무것도 아닙니다.
    MessageJP: いえ、何でもありません
    MessageCN: 没有，没什么
    MessageEN: Never mind.
    MessageTH: ไม่มีอะไรหรอกค่ะ
    MessageTW: 不，沒什麼
  - MessageGroupId: 260010090
    Id: 1568
    CharacterId: 26001
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 260010080
    PreConditionFavorScheduleId: 260012
    FavorScheduleId: 0
    NextGroupId: 260010100
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, <메리 씨의 전화>라는 괴담을 알고 있으신가요?
    MessageJP: 先生、「メリーさんの電話」という怪談をご存知ですか？
    MessageCN: 老师知道“玛丽的电话”这个怪谈吗?
    MessageEN: Have you heard of a ghost story called Mary's Calling, Sensei?
    MessageTH: 'คุณครูรู้จักเรื่องเล่า "โทรศัพท์ของแมรี่"

      รึเปล่าคะ?'
    MessageTW: 老師，你有聽過「瑪莉的電話」這個鬼故事嗎？
  - MessageGroupId: 260010100
    Id: 1569
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 잘 모르겠는데.
    MessageJP: 聞いたことないかも
    MessageCN: 好像没有听说过
    MessageEN: Never heard of it.
    MessageTH: อืม ไม่รู้จักแฮะ
    MessageTW: 好像沒聽過
  - MessageGroupId: 260010110
    Id: 1570
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010120
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ''
    MessageKR: <메리 씨의 전화>는 어느 소녀가 메리라는 이름의 인형을 버리자, 그 인형이 소녀에게 직접 전화를 걸어온다는 내용의 괴담입니다.
    MessageJP: ある少女の元に、昔捨てたはずのメリーという人形から電話が来るんです
    MessageCN: 从前有个少女接到了她的洋娃娃玛丽的电话，但她明明已经把玛丽扔掉了
    MessageEN:
      Mary's Calling is a scary story about a little girl with a doll named
      Mary. When the girl throws the doll away, the doll starts calling for her.
    MessageTH: '"โทรศัพท์ของแมรี่" เป็นเรื่องราวสยอง

      ขวัญเกี่ยวกับเด็กสาวคนหนึ่งที่ทิ้งตุ๊กตา

      ที่ชื่อว่าแมรี่ไป และแมรี่ก็โทรศัพท์กลับ

      ไปหาเด็กผู้หญิงคนนั้นค่ะ'
    MessageTW: 有個少女某天接到了一通電話，是她以前丟掉的，一個名叫瑪莉的人偶打來的
  - MessageGroupId: 260010110
    Id: 1571
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010120
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR:
      이 괴담의 무서운 포인트는 전화를 걸 때마다 메리의 위치가 점점 소녀에게 가까워지다가 마지막에는 등 뒤에서 인형이 나타난다는
      점이지요.
    MessageJP: 怖いのは、電話が来るたびにメリーさんが徐々に近づいてくるという……
    MessageCN: 更可怕的是，每次来电话的时候，玛丽都会逐渐靠近……
    MessageEN:
      The scary part is that each time Mary calls the little girl, she gets
      closer and closer to her. At the end, the doll appears right behind the little
      girl.
    MessageTH: 'ความน่ากลัวของเรื่องนี้ก็คือ ทุกครั้งที่

      โทรศัพท์ ตำแหน่งของแมรี่ก็จะขยับเข้า

      ไปใกล้บ้านของเด็กสาวทุกครั้ง และ

      สุดท้ายตุ๊กตาแมรี่ก็ไปโผล่ที่ด้านหลัง

      ของเด็กสาวค่ะ'
    MessageTW: 可怕的是，每次電話打過來的時候，瑪莉就會慢慢的靠近……
  - MessageGroupId: 260010120
    Id: 1572
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 그런데 갑자기 괴담은 왜?
    MessageJP: そういう話なんだ……ところで、どうして急にそんな怪談を？
    MessageCN: 原来是这样的故事啊……话说回来，为什么小玉突然提到这种怪谈呢？
    MessageEN: And why are you telling me this?
    MessageTH: ทำไมจู่ๆ ถึงเล่าเรื่องสยองขวัญขึ้นมาล่ะ?
    MessageTW: 原來是這樣啊……話說為什麼突然要講鬼故事？
  - MessageGroupId: 260010130
    Id: 1573
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그냥, 갑자기 궁금해져서 그렇습니다.
    MessageJP: 特に意味はありません、何となくです
    MessageCN: 没有什么特别的意思，就是突然想到了而已
    MessageEN: I don't know. I was just curious if you'd heard of it.
    MessageTH: แค่จู่ๆ ก็สงสัยขึ้นมาน่ะค่ะ
    MessageTW: 沒什麼特別的意思，心血來潮而已
  - MessageGroupId: 260010140
    Id: 1574
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010150
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 이 전화를 역추적한다면 메리 씨는 어디서 전화를 걸고 있는 것으로 표시될까요?
    MessageJP: ……その電話を逆探知したら、メリーさんの居場所が分かりますね
    MessageCN: ……如果对那个电话进行逆向追踪的话，就能找到玛丽小姐在的地方了呢
    MessageEN:
      If you could trace back her calls, I wonder if you would see where
      Mary is calling from?
    MessageTH: 'ถ้าเกิดว่าเราแกะรอยโทรศัพท์นี้ไป มันจะ

      แสดงพิกัดรึเปล่าว่าแมรี่โทรมาจากที่ไหน?'
    MessageTW: ……如果反追蹤那個電話號碼的話，應該就能知道瑪莉在哪裡了
  - MessageGroupId: 260010140
    Id: 1575
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 언젠가 메리 씨가 제 핸드폰에도 전화를 걸어왔으면 좋겠습니다.
    MessageJP: メリーさん、私のスマホに電話をかけてきてくれないでしょうか
    MessageCN: 玛丽小姐，能不能给我打个电话呢
    MessageEN: I wish Mary would call me sometime.
    MessageTH: 'บางครั้งฉันก็รู้สึกอยากให้แมรี่โทรมาหา

      ฉันบ้างเหมือนกันค่ะ'
    MessageTW: 瑪莉，能不能打電話給我呢
  - MessageGroupId: 260010150
    Id: 1576
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260013
    NextGroupId: 260010160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무, 무서워……!
    MessageJP: 怖いよ……
    MessageCN: 太吓人了吧……
    MessageEN: How spooky!
    MessageTH: นะ...น่ากลัวสุดๆ...!
    MessageTW: 好可怕……
  - MessageGroupId: 260010160
    Id: 1577
    CharacterId: 26001
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 260010150
    PreConditionFavorScheduleId: 260013
    FavorScheduleId: 0
    NextGroupId: 260010170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 선생님, 혹시 최근에 이상한 내용의 전화를 받으신 적은 없으십니까?
    MessageJP: 先生、もしかして最近、変な電話がかかってきませんでしたか？
    MessageCN: 老师最近有没有接到奇怪的电话?
    MessageEN: Have you received any strange calls lately?
    MessageTH: 'คุณครูคะ... คุณครูเคยได้รับโทรศัพท์

      แปลกๆ บ้างรึเปล่าคะ?'
    MessageTW: 老師，難道說你最近有接到奇怪的電話嗎？
  - MessageGroupId: 260010170
    Id: 1578
    CharacterId: 26001
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 뭔가 위험해 보이는 사람이 위험한 말을 한다든가…….
    MessageJP: 怖い人から通話がかかってきたとか、怪しい内容の電話が来たとか……
    MessageCN: 比如说从可怕的人那里打来的电话，或者内容奇怪的电话……
    MessageEN: Like, has a suspicious person said anything scary to you?
    MessageTH: อย่างเช่นมีคนน่ากลัวโทรมาพูดจาข่มขู่...
    MessageTW: 像是可怕的人打來的電話，或是內容很奇怪的電話之類的……
  - MessageGroupId: 260010180
    Id: 1579
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 특별히 기억에 남는 전화는 없는데. 왜?
    MessageJP: 特に無かったと思うけど、どうして？
    MessageCN: 好像没有什么特别奇怪的，怎么了？
    MessageEN: Not that I can recall. Why?
    MessageTH: 'ครูจำไม่ได้นะว่าเคยมีคนโทรมา

      ทำไมเหรอ?'
    MessageTW: 好像沒什麼特別的電話，怎麼了嗎？
  - MessageGroupId: 260010190
    Id: 1580
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 그게 사실은…….
    MessageJP: 実は……
    MessageCN: 其实……
    MessageEN: The truth is...
    MessageTH: ที่จริงแล้ว...
    MessageTW: 其實……
  - MessageGroupId: 260010200
    Id: 1581
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260015
    NextGroupId: 260010210
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ''
    MessageKR: 아니, 나중에 말씀드리겠습니다.
    MessageJP: いえ、後ほど直接お話します
    MessageCN: 没什么，之后我和老师当面说吧
    MessageEN: Never mind. I'll tell you next time.
    MessageTH: ไม่มีอะไรหรอกค่ะ ไว้ฉันจะเล่าให้ฟังนะคะ
    MessageTW: 不，我之後直接跟你說
  - MessageGroupId: 260010210
    Id: 260010010
    CharacterId: 26001
    MessageCondition: FavorRankUp
    ConditionValue: 6
    PreConditionGroupId: 260010200
    PreConditionFavorScheduleId: 260015
    FavorScheduleId: 0
    NextGroupId: 260010220
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: ……아.
    MessageJP: ……あ
    MessageCN: ……啊
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010220
    Id: 260010020
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010230
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 무슨 일이야?
    MessageJP: どうしたの？
    MessageCN: 怎么啦？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010230
    Id: 260010030
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010240
    FeedbackTimeMillisec: 2500
    MessageType: Text
    ImagePath: ''
    MessageKR: 그게…… 컴퓨터와 연결된 이어폰을 착용하고 있다는 사실을 잊은 채 자리에서 일어나는 바람에 의자 위로 넘어질 뻔했습니다.
    MessageJP: パソコンにイヤホンを繋げたまま立ち上がって、危うく転びそうに
    MessageCN: 耳机还插在电脑上就站起来了，差点把电脑带到地上
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010240
    Id: 260010040
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 음악에 몰두하다보면 흔히 있는 일이지.
    MessageJP: 夢中になってるとよくあるよね
    MessageCN: 如果专注起来的话经常会发生这种事呢
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010250
    Id: 260010050
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010260
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 네, 의외로 사람의 청각은 반복되는 자극에 쉽게 무디어지는 법이니까요.
    MessageJP: はい。聴覚というものは、繰り返しの刺激には簡単に慣れてしまうものですから
    MessageCN: 是的。毕竟听觉是很容易习惯机械刺激的
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010260
    Id: 260010060
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010270
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 코타마는 평소에는 주로 어떤 음악을 들어?
    MessageJP: コタマは普段、どんな音楽を聴くの？
    MessageCN: 小玉平时会听什么样的音乐呢？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010270
    Id: 260010070
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010280
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 제가 듣는 음악, 말입니까?
    MessageJP: 私がよく聞く音楽……
    MessageCN: 我经常听的音乐……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010280
    Id: 260010080
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010290
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 어, 그게…….
    MessageJP: えっと、それは……
    MessageCN: 嗯，这个嘛……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010280
    Id: 260010090
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010290
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: …….
    MessageJP: ……
    MessageCN: ……
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010290
    Id: 260010100
    CharacterId: 26001
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260010300
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ''
    MessageKR: 비밀입니다.
    MessageJP: 秘密です
    MessageCN: 保密
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
  - MessageGroupId: 260010300
    Id: 260010110
    CharacterId: 26001
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260016
    NextGroupId: 0
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ''
    MessageKR: 어째서?!
    MessageJP: なんで！？
    MessageCN: 为什么！？
    MessageEN: ''
    MessageTH: ''
    MessageTW: ''
