CharacterId: 26013
translator: acetone
title:
  - TextJp: 形がなくとも残るもの
    TextCn: 无形却长存的东西
    TextKr: 보이지 않아도 남는 것
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601302
    FavorScheduleId: 260132
    CharacterId: 26013
  - TextJp: 逃げた先にあるもの
    TextCn: 在逃亡前方的东西
    TextKr: 도망친 곳에 꽃밭은 있다
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601303
    FavorScheduleId: 260133
    CharacterId: 26013
  - TextJp: 最後に撮ったもの
    TextCn: 最后定格下的东西
    TextKr: 마지막으로 찍고 싶은 것
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601305
    FavorScheduleId: 260135
    CharacterId: 26013
content:
  - MessageKR: 선생님, 안녕.
    MessageJP: こんにちは、先生
    MessageCN: 你好，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130010
    Id: 260130010
    CharacterId: 26013
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 안녕, 아츠코.
    MessageJP: こんにちは、アツコ
    MessageCN: 你好，亚津子
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130020
    Id: 260130020
    CharacterId: 26013
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130030
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 바다에 오는 거, 기대한 보람이 있었어.
    MessageJP: 海、思っていた以上にきれいで
    MessageCN: 大海，比我想象中的更漂亮
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130030
    Id: 260130030
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 어디든 눈을 뗄 수가 없는 걸.
    MessageJP: 目が離せないの
    MessageCN: 看得眼睛都挪不开了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130030
    Id: 260130040
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130040
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 바다도, 축제도, 처음 보는 것 투성이라서.
    MessageJP: お祭りも、初めて見るものばかり
    MessageCN: 祭典里也是，到处都是第一次见的新鲜东西
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130040
    Id: 260130050
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130050
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 즐기고 있는 것 같아 다행이네.
    MessageJP: 楽しめてるみたいで良かった！
    MessageCN: 亚津子喜欢就太好了！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130050
    Id: 260130060
    CharacterId: 26013
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130060
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응, 모처럼이니 사진으로도 남기려고 해.
    MessageJP: せっかくだから、写真を残したい
    MessageCN: 难得来一次，我想拍一些照片
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130060
    Id: 260130070
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 해변가에서 사진 찍을 만한 포인트를 찾아다닐 생각인데
    MessageJP: ちょっと出かけてくる
    MessageCN: 我打算在海边寻找值得拍照的地方
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130060
    Id: 260130080
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130070
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님도 같이 어때?
    MessageJP: 先生も一緒に、どう？
    MessageCN: 老师能和我一起吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130070
    Id: 260130090
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260132
    NextGroupId: 260130080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130080
    Id: 260130100
    CharacterId: 26013
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 260130070
    PreConditionFavorScheduleId: 260132
    FavorScheduleId: 0
    NextGroupId: 260130090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 바빠?
    MessageJP: 今、忙しい？
    MessageCN: 现在忙吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130090
    Id: 260130110
    CharacterId: 26013
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아냐, 지금 한가해.
    MessageJP: 時間ならあるよ
    MessageCN: 现在有时间的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130100
    Id: 260130120
    CharacterId: 26013
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그럼 잠깐 어울려줘.
    MessageJP: じゃあ、少し付き合ってくれる？
    MessageCN: 那，能稍微陪陪我吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130110
    Id: 260130130
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 꼭 찍고 싶은 게 두 가지 생겼거든.
    MessageJP: どうしても、撮りたいものが2つあって
    MessageCN: 我有两个特别想拍的东西
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130110
    Id: 260130140
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아
    MessageJP: あ
    MessageCN: 啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130120
    Id: 260130150
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이번에는 확실히 배터리를 넣었으니까.
    MessageJP: 今度はちゃんと、バッテリーを入れていくから
    MessageCN: 这次我会装好电池的
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130120
    Id: 260130160
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260133
    NextGroupId: 260130130
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님
    MessageJP: 先生
    MessageCN: 老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130130
    Id: 260130170
    CharacterId: 26013
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 260130120
    PreConditionFavorScheduleId: 260133
    FavorScheduleId: 0
    NextGroupId: 260130140
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 안 좋은 소식이 있어.
    MessageJP: 悪いお知らせだよ
    MessageCN: 有个坏消息
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130140
    Id: 260130180
    CharacterId: 26013
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130150
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 무슨 일이야?
    MessageJP: どうしたの？
    MessageCN: 怎么了？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130150
    Id: 260130190
    CharacterId: 26013
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 디지털카메라의 배터리가 얼마 남지 않았어.
    MessageJP: カメラのバッテリーが、あと少ししかなくて
    MessageCN: 相机的电池，电量只剩一点点了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130160
    Id: 260130200
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 아직 작동은 하지만, 아껴 써야 해.
    MessageJP: もう何枚も撮れないの
    MessageCN: 已经拍不了几张照片了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130160
    Id: 260130210
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260130170
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이제부터는 뭘 찍을지 신중하게 정해서 찍을 생각이야.
    MessageJP: だから、何を撮るか慎重に決めないと
    MessageCN: 所以，必须要慎重地决定要拍什么
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260130170
    Id: 260130220
    CharacterId: 26013
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260135
    NextGroupId: 0
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
