CharacterId: 26012
translator: 6e609a
title:
  - TextJp: 人命救助訓練
    TextCn: 救生训练
    TextKr: 수상안전을 위한 노력
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601202
    FavorScheduleId: 260122
    CharacterId: 26012
  - TextJp: 心肺蘇生法
    TextCn: 心肺复苏法
    TextKr: 응급상황을 위한 대비
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601203
    FavorScheduleId: 260123
    CharacterId: 26012
  - TextJp: 総合救護実習
    TextCn: 综合救护实习
    TextKr: 종합 구조 실습
    TextEn: ""
    TextTh: ""
    TextTw: ""
    GroupId: 2601205
    FavorScheduleId: 260125
    CharacterId: 26012
content:
  - MessageKR: 안녕하세요, 선생님.
    MessageJP: こんにちは、先生
    MessageCN: 您好，老师
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120010
    Id: 260120010
    CharacterId: 26012
    MessageCondition: FavorRankUp
    ConditionValue: 2
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120020
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 본관에게 도움을 주실 수 있으신가요……?
    MessageJP: どうか、本官を助けていただけませんか……？
    MessageCN: 您能不能帮帮本官……？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120020
    Id: 260120020
    CharacterId: 26012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120030
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론이지. 어떤 도움이 필요한데?
    MessageJP: もちろんだよ
    MessageCN: 当然可以啦
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120030
    Id: 260120030
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120040
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 본관, 이번에 라이프가드 임무를 맡게 되었습니다.
    MessageJP: 実は本官、この度ライフセーバーの任務を命じられました
    MessageCN: 其实，本官这次接到了担当救生员的任务。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120040
    Id: 260120040
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120050
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 시민들의 안전을 지키는 경관으로서 더할 나위 없는 영광입니다만…….
    MessageJP: 市民の安全を守る警官として、光栄なのですが……
    MessageCN: 虽然作为保护市民安全的警察，我感到很光荣……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120040
    Id: 260120050
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120050
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그게…….
    MessageJP: その……
    MessageCN: 但是……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120050
    Id: 260120060
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120060
    FeedbackTimeMillisec: 100
    MessageType: Text
    ImagePath: ""
  - MessageKR: 평범한 수영이라면 가능하지만, 수상 인명 구조를 위한 영법이 따로 있다고 합니다.
    MessageJP: 水上で人命救助を行なった経験がなくてですね
    MessageCN: 本官没有水上救生的经验。
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120050
    Id: 260120070
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120060
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 게다가 이 사실을 어제 알게 됐어요…….
    MessageJP: 特別な訓練を積む必要があると、昨日になって知りました……
    MessageCN: 我昨天才知道必须接受特别的训练……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120050
    Id: 260120080
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120060
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그러면 큰일이잖아?
    MessageJP: それは大変だね……
    MessageCN: 那可不得了啊……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120060
    Id: 260120090
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 지금이라도 연습해야 하는 거 아냐?
    MessageJP: 練習、間に合いそう？
    MessageCN: 练习还来得及吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120060
    Id: 260120100
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120070
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 혹시 선생님께서 수영 연습을 도와주실 수 있으신가요?!
    MessageJP: そこでご相談がありまして……
    MessageCN: 正是因此，所以想和您商量一下
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120070
    Id: 260120110
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 이대로라면 본관, 임무 부적합 판정을 받을지도 모릅니다!
    MessageJP: 訓練に付き合っていただきたいのです！
    MessageCN: 想请您陪我训练！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120070
    Id: 260120120
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260122
    NextGroupId: 260120080
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님, 안녕하세요.
    MessageJP: 先生、こんにちは
    MessageCN: 老师，您好
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120080
    Id: 260120130
    CharacterId: 26012
    MessageCondition: FavorRankUp
    ConditionValue: 3
    PreConditionGroupId: 260120070
    PreConditionFavorScheduleId: 260122
    FavorScheduleId: 0
    NextGroupId: 260120090
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저번 연습 이후 오랫동안 생각해 본 바…….
    MessageJP: あれから考えてみましたが……
    MessageCN: 那之后我想了想……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120090
    Id: 260120140
    CharacterId: 26012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120100
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 역시 빠른 시간 내에 구조 영법을 배우는 건 힘들 것 같습니다.
    MessageJP: やはり、今から訓練をしても間に合いそうもありません
    MessageCN: 现在开始训练好像也来不及了!
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120090
    Id: 260120150
    CharacterId: 26012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120100
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 으응, 아무래도 익숙지 않으니까…….
    MessageJP: 1日2日じゃ難しいよね……
    MessageCN: 就一两天的时间还是紧张了啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120100
    Id: 260120160
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120110
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그러니 본관은 응급처치에 집중하기로 했습니다!
    MessageJP: なので本官は、応急処置に専念することにしました！
    MessageCN: 因此本官决定专心训练应急处理！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120110
    Id: 260120170
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120120
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 누군가 익수자를 물에서 구조하면, 그때 본관이 정신을 차릴 수 있도록 조치하는 거죠!
    MessageJP: 落水者の生存率を少しでも上げるために！
    MessageCN: 为了尽可能提高落水者的生存率！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120110
    Id: 260120180
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120120
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 방향을 바꿨구나?
    MessageJP: 方針を変えたんだね
    MessageCN: 改变方针了啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120120
    Id: 260120190
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 맞아, 그것도 중요한 일이지.
    MessageJP: たしかに、それも大事だよね
    MessageCN: 的确，这也很重要啊
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120120
    Id: 260120200
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120130
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 네! 선생님께서 괜찮으시다면, 이번에도 훈련을 참관해 주셨으면 합니다!
    MessageJP: はい！先生がよろしければ、今回も訓練に付き合っていただいても良いでしょうか？
    MessageCN: 是的！如果老师方便的话，这次也可以陪我一起训练吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120130
    Id: 260120210
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120140
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 저번과 같은 실수는 하지 않을 테니 안심하셔도 좋습니다!
    MessageJP: 前回のような失敗はしないので、ご安心ください！
    MessageCN: 我不会再犯上次那样的错误了，请放心！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120130
    Id: 260120220
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260123
    NextGroupId: 260120140
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님, 혹시 매뉴얼을 읽으셨나요?
    MessageJP: ……先生、もしかしてマニュアルを読みましたか？
    MessageCN: ……老师，你是不是读了手册了？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120140
    Id: 260120230
    CharacterId: 26012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 260120130
    PreConditionFavorScheduleId: 260123
    FavorScheduleId: 0
    NextGroupId: 260120150
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 응, 읽었어.
    MessageJP: うん、読んだよ
    MessageCN: 嗯，读过了
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120150
    Id: 260120240
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120160
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 훈련 때는 하지 않았지만, 실제로 내가 빠지면 해줄 거지?
    MessageJP: もし私が溺れたら、キリノは助けてくれるんだよね？
    MessageCN: 如果我溺水了，桐乃会救我吧？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120160
    Id: 260120250
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120170
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 무
    MessageJP: も
    MessageCN: 那
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120170
    Id: 260120260
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120180
    FeedbackTimeMillisec: 500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론입니다!
    MessageJP: もちろんです！
    MessageCN: 那当然！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120170
    Id: 260120270
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120180
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 본관은 공과 사를 확실히 구분할 줄 아는 경관이니까요!
    MessageJP: 本官は、公私の区別をつけられる警官なので！
    MessageCN: 因为本官是公私分明的警察！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120170
    Id: 260120280
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120180
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 제세동기를 말한 건데?
    MessageJP: AEDのことを言ってるんだけど……
    MessageCN: 我说的是AED……
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120180
    Id: 260120290
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120190
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 보, 본관을 놀리지 말아 주세요!
    MessageJP: ほ、本官をからかわないでください！
    MessageCN: 请，请不要捉弄本官！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120190
    Id: 260120300
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120200
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님! 안녕하십니까! 키리노입니다!
    MessageJP: 先生！こんにちは、キリノです！
    MessageCN: 老师！您好，我是桐乃！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120200
    Id: 260120310
    CharacterId: 26012
    MessageCondition: FavorRankUp
    ConditionValue: 5
    PreConditionGroupId: 260120190
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120210
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님의 도움 덕에 라이프가드 임무를 위한 훈련을 마치고, 이제 마지막 점검을 하려 합니다.
    MessageJP: 先生のおかげで、ライフセーバーの訓練が終了しました！
    MessageCN: 托老师的福，救生员的训练结束了！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120210
    Id: 260120320
    CharacterId: 26012
    MessageCondition: None
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120220
    FeedbackTimeMillisec: 2000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 축하해, 키리노.
    MessageJP: おめでとう、キリノ
    MessageCN: 恭喜你，桐乃
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120220
    Id: 260120330
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120230
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 선생님께서 물심양면으로 도와주신 덕분입니다!
    MessageJP: これも先生が協力してくださったおかげです！
    MessageCN: 这也多亏了老师的协助！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120230
    Id: 260120340
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120240
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 그런 뜻에서 훈련의 마무리에 참관을 요청드릴까 하는데, 혹시 괜찮으신가요?
    MessageJP: 最後に訓練の復習をしようと思っているのですが、また付き合っていただけないでしょうか？
    MessageCN: 我想最后复习一下，请问还能再陪我一下吗？
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120230
    Id: 260120350
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120240
    FeedbackTimeMillisec: 1500
    MessageType: Text
    ImagePath: ""
  - MessageKR: 물론이지. 꼭 갈게.
    MessageJP: もちろん行くよ
    MessageCN: 当然可以
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120240
    Id: 260120360
    CharacterId: 26012
    MessageCondition: Answer
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 260120250
    FeedbackTimeMillisec: 0
    MessageType: Text
    ImagePath: ""
  - MessageKR: 감사합니다!
    MessageJP: ありがとうございます！
    MessageCN: 谢谢！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120250
    Id: 260120370
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 0
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
  - MessageKR: 마침내 유종의 미를 거둘 수 있겠네요!
    MessageJP: 今度こそ、成長した姿をお見せしましょう！
    MessageCN: 这次一定要让老师看到本官成长的样子！
    MessageEN: ""
    MessageTH: ""
    MessageTW: ""
    MessageGroupId: 260120250
    Id: 260120380
    CharacterId: 26012
    MessageCondition: Feedback
    ConditionValue: 0
    PreConditionGroupId: 0
    PreConditionFavorScheduleId: 0
    FavorScheduleId: 260125
    NextGroupId: 0
    FeedbackTimeMillisec: 1000
    MessageType: Text
    ImagePath: ""
